<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">
				<h3 class="tit">Cadastrar Menu Web</h3>
				<hr />   
				<form action="/menu-web/cadastro" method="post">
                        <div class="col-xs-8 col-md-8">
                            <label>Menu: </label>
                            <input class="form-control" type="text" name="ds_menu" maxlength="50" placeholder="Nome do menu" required />
                        </div>

                        <div class="col-xs-8 col-md-8">
                            <label>Menu Pai: </label>
                            <select name="cd_menu_pai" class="form-control">
                                <option VALUE="">Selecione...</option>
                                <?php foreach( $menuPai as $menu){
                                    echo '<option value="'.$menu['cd_menu'].'">"'.$menu['cd_menu'] . ' - ' . utf8_encode($menu['ds_menu']) .'</option>';
                                }?>
                            </select>
                        </div>

                        <div class="col-xs-6 col-md-6">
                            <label>Url: </label>
                            <input class="form-control" type="text" name="ds_url" maxlength="50" placeholder="Url para acesso do menu" />
                        </div>

                        <div class="col-xs-6 col-md-6">
                            <label>Ícone: </label>
                            <input class="form-control" type="text" name="ds_icone" maxlength="50" placeholder="Icone do menu ,se Menu Pai" />
                        </div>

                        <div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/menu-web/index"><button type="button" class="btn btn-default">
                                    <i class="i i-back"></i>
									Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
			