<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<section class="panel panel-default">

    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de Menus do Sistema</h3>
                </div>
            </div>
        </div>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                        <tr >
                            <th nowrap>#</th>
                            <th nowrap>Menu</th>
                            <th nowrap>Menu Pai</th>
                            <th nowrap>Url</th>
                            <th nowrap>Ícone</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (count($menus)) : ?>
                            <?php foreach ($menus as $dado): ?>
                                <tr>
                                    <td align="right"><?php echo $dado['CD_MENU']  ?></td>
                                    <td align="left"><?php echo utf8_encode($dado['DS_MENU']) ?></td>
                                    <td align="right"><?php echo $dado['CD_MENU_PAI']  ?></td>
                                    <td align="left"><?php echo utf8_encode($dado['DS_URL']) ?></td>
                                    <td align="left"><?php echo utf8_encode($dado['DS_ICONE']) ?></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th nowrap>#</th>
                            <th nowrap>Menu</th>
                            <th nowrap>Menu Pai</th>
                            <th nowrap>Url</th>
                            <th nowrap>Ícone</th>
                        </tr>
                        </tfoot>
                    </table>
                    <?php echo $this->paginationControl($menus, 'Sliding', 'partials/paginator/control-no-form.phtml') ?>
                </div>
            </div>
        </div>
    </div>
</section>