<section class="panel panel-default">
      <div class="main_container">
              <!-- bar charts group -->
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Relatório <small>Grafíco - Tipo de Pagamento</small> <h6>Data 01/03/2017</h6></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content1">
                    <div id="graph_bar_group" style="width:100%; height:280px;"></div>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
              <div class="clearfix"></div>
              <!-- /bar charts group -->
      </div>


    <script type="text/javascript" src="/relatorios/raphael/raphael.min.js"></script>
    <script type="text/javascript" src="/relatorios/morris.js/morris.min.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>


    <script>
      $(document).ready(function() {

        Morris.Bar({
          element: 'graph_bar_group',
          data: [
            {"data": "Loja 1", "Dinheiro": 807, "Cartao": 660, "Outros": 789},
            {"data": "Loja 2", "Dinheiro": 635, "Cartao": 541, "Outros": 654},
            {"data": "Loja 3", "Dinheiro": 365, "Cartao": 421, "Outros": 321},
            {"data": "Loja 4", "Dinheiro": 984, "Cartao": 669, "Outros": 987},
            {"data": "Loja 5", "Dinheiro": 914, "Cartao": 345, "Outros": 456}
          ],
          xkey: 'data',
          barColors: ['#26B99A', '#34495E', '#ACADAC', '#EEB422','#8A2BE2','#A2B5CD'],
          ykeys: ['Dinheiro', 'Cartao', 'Outros'],
          labels: ['Dinheiro', 'Cartão', 'Outros'],
          hideHover: 'auto',
          xLabelAngle: 60,
          resize: true
        });


        $MENU_TOGGLE.on('click', function() {
          $(window).resize();
        });
      });
    </script>
    <!-- /morris.js -->      


</section>
            