<section class="panel panel-default">

    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <i class="icon-check"></i>
                    <h3><?php echo "Relat&oacute;rio de Atendimento - Produtos / Servi&ccedil;os Vendidos" ?></h3>
                </div>

                <div class="widget-content">
                    <form id="formRelatorio" target="self" class="form-vertical" id="validation-form" action="/relatorio-atendimento/relatorio">
                        <input type="hidden" id="pdf" name="pdf" value="false" />

                        <div class="controls">
                           <!-- <div class="col-md-2">
                                <label for="" class="control-label text-info"><?php /*echo utf8_encode("De") */?></label>
                                <div class="input-append date" id="dp1" data-date="" data-date-format="dd/mm/yyyy" >
                                    <input class="form-control" size="16" type="text" value="" id="dtInicio" name="dtInicio" required>
                                    <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <label for="" class="control-label text-info"><?php /*echo utf8_encode("At&eacute;") */?></label>
                                <div class="input-append date" id="dp2" data-date="" data-date-format="dd/mm/yyyy" >
                                    <input class="form-control" size="16" type="text" value="" id="dtTermino" name="dtTermino" required>
                                    <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                                </div>
                            </div>-->

                            <div class="col-md-3">
                                <label for="" class="control-label text-info"><?php echo utf8_encode("De") ?></label>
                                <input type="text" class="dataP form-control" id="dtInicio" name="dtInicio"  required autocomplete="off" value="<?php echo  date("d-m-Y") ?>">
                                <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                            </div>

                            <div class="col-md-3">
                                <label for="" class="control-label text-info"><?php echo utf8_encode("At&eacute;") ?></label>
                                <input type="text" class="dataP form-control" id="dtTermino" name="dtTermino"  required  autocomplete="off" value="<?php echo  date("d-m-Y") ?>">
                                <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                            </div>


                            <div class="col-lg-12">
                                <hr>
                                <button id="btnPesquisarRelatorio" class="btn btn-primary btn" type="submit"><i class="icon-search icon-white"></i>&nbsp;Pesquisar</button>
                                <button id="btnCancelarRelatorio" class="btn btn-default btn" type="reset"><i class="icon-remove icon-white"></i>&nbsp;Limpar</button>
                                <button id="btnVoltarRelatorio"    class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>
                            </div>
                        </div>

                    </form>
                </div> <!-- /widget-content -->
            </div> <!-- /widget -->
        </div> <!-- /span12 -->
    </div>
</div>
<div id="modalDadosRelatorio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalDadosRelatorio" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="pull-right btn btn-danger"  id="btnFechar"></i>Fechar</button>
                <button type="button" class="pull-right btn btn-primary"  id="btnGerarPDF"></i>PDF</button>
                <span class="text-info-modal"><i class="icon-white icon-check"></i><?php echo "Relat&oacute;rio de Atendimento - Produtos / Servi&ccedil;os Vendidos" ?></span>
            </div>
            <div id="modalBodyDadosRelatorio" class="container-fluid" style="overflow-y:scroll"></div>
        </div>
    </div>
</div>
</section>
<script>
    $(document).ready(function() {

        $('.dataP').datepicker(
            {
                format: 'dd-mm-yyyy',
                language: 'pt-BR',
                todayBtn: "linked"
            }
        );

        $('#formRelatorio').submit(function()
        {
            if ($("#pdf").val() == "false")
            {

                $("#modalBodyDadosRelatorio").load('/relatorio-atendimento/relatorio', {
                    dtInicio: $("#dtInicio").val(),
                    dtTermino: $("#dtTermino").val()
                });
                $("#modalDadosRelatorio").modal('show');
                return false;
            }
            else
            {
                return true;
            }

        });

        $('#btnGerarPDF').click(function() {
            $("#pdf").val("true");
            $("#formRelatorio").submit();
        });


        $('#btnFechar').click(function() {
            $("#pdf").val("false");
            $("#modalDadosRelatorio").modal('hide');
        });


        $('#btnVoltarRelatorio').click(function() {
            window.location = '/relatorio/index';
        });


    });
</script>