<section class="panel panel-default">

    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <i class="icon-check"></i>
                    <h3><?php echo utf8_encode("Relat&oacute;rio Invent&aacute;rio de Estoque") ?></h3>
                </div>
                <div class="widget-content">
                    <form id="formRelatorio" target="self" class="form-vertical validation-form" action="/relatorio-inventario-estoque/relatorio">
                        <input type="hidden" id="pdf" name="pdf" value="false" />

                        <div class="col-md-6">
                            <label for="" class="control-label text-info"><?php echo utf8_encode("Tipo Mercadoria / Se&ccedil;&atilde;o") ?></label>
                            <br>
                            <select class="form-control" id="cdTipoMercadoria" name="cdTipoMercadoria">
                                <option value="">Selecione...</option>
                                <?php
                                foreach ($listaTipoMercadoria as $tipoMercadoria) {
                                    echo "<option value='{$tipoMercadoria["CD_TIPO_MERCADORIA"]}'>{$tipoMercadoria["CD_TIPO_MERCADORIA"]} - " . utf8_encode($tipoMercadoria["DS_TIPO_MERCADORIA"]) . "</option>";
                                }
                                ?>
                            </select>
                        </div>
                        <!--
                       <div class="span12">
                               <label for="" class="control-label text-info"><?php //echo utf8_encode("Fornecedor")    ?></label>
                           <select class="span6" id="cdFornecedor" name="cdFornecedor">
                            <option value="">Selecione...</option>
                        <?php
                        //foreach ($listaFornecedor as $fornecedor) {
                        //echo "<option value='{$fornecedor["CD_FORNECEDOR"]}'>{$fornecedor["CD_FORNECEDOR"]} - {$fornecedor["SG_FORNECEDOR"]}".utf8_encode($fornecedor["DS_FANTASIA"])."</option>";
                        //}
                        ?>
                           </select>
                       </div>
                        -->
                        <div class="col-md-2">
                            <label for="" class="control-label text-info"><?php echo utf8_encode("De") ?></label>
                            <div class="input-append date" id="dp1" data-date="" data-date-format="dd/mm/yyyy" >
                                <input class="form-control" size="16" type="text" value="" id="dtInicio" name="dtInicio" required>
                                <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label for="" class="control-label text-info"><?php echo utf8_encode("At&eacute;") ?></label>
                            <div class="input-append date" id="dp2" data-date="" data-date-format="dd/mm/yyyy" >
                                <input class="form-control" size="16" type="text" value="" id="dtTermino" name="dtTermino" required>
                                <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label for="" class="control-label text-info"><?php echo utf8_encode("Livro de pre&ccedil;os") ?></label>
                            <select name="nrLivroPreco" id="nrLivroPreco" class="form-control" required>

                                <?php
                                foreach ($listaLivroPreco as $livro) {
                                    echo "<option value='{$livro["CD_LIVRO"]}'>0{$livro["CD_LIVRO"]}</option>";
                                }
                                ?>
                            </select>

                        </div>

                        <div class="col-md-6">
                            <br>
                            <label>
                                <input type="checkbox" name="estoquePositivo" id="estoquePositivo" value="1" />&nbsp;Incluir apenas mercadoria com estoque positivo
                            </label>
                            <br>
                        </div>

                        <div class="col-md-12">
                            <label for="" class="control-label text-info"><?php echo utf8_encode("Ordenar por") ?></label>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="rdbOrdenar" id="rdbOrdenar_M" value="M" checked/>&nbsp;Produto / Servi&ccedil;o
                                </label>
                                <label>
                                    <input type="radio" name="rdbOrdenar" id="rdbOrdenar_G" value="G" checked/>&nbsp;Grupo / SubGrupo
                                </label>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <hr>
                            <button id="btnPesquisarRelatorio" class="btn btn-primary btn" type="submit"><i class="icon-search icon-white"></i>&nbsp;Pesquisar</button>
                            <button id="btnCancelarRelatorio" class="btn btn-default btn" type="reset"><i class="icon-remove icon-white"></i>&nbsp;Limpar</button>
                            <button id="btnVoltarRelatorio"    class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>

                        </div>

                    </form>
                </div> <!-- /widget-content -->
            </div> <!-- /widget -->
        </div> <!-- /span12 -->
    </div>

    <div id="modalDadosRelatorio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalDadosRelatorio" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="pull-right btn btn-danger"  id="btnFechar">Fechar</button>
                    <button type="button" class="pull-right btn btn-primary"  id="btnGerarPDF"><i class="icon-file"></i>PDF</button>
                    <span class="text-info-modal"><i class="icon-white icon-check"></i><?php echo utf8_encode("Relat&oacute;rio Invent&aacute;rio de Estoque") ?></span>
                </div>
                <div id="modalBodyDadosRelatorio" class="container-fluid" style="max-height:410pt; overflow-y:scroll"></div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {
        $('#dp1,#dp2').datepicker();

        $('#formRelatorio').submit(function()
        {
            if ($("#pdf").val() == "false")
            {

                var vEstoquePositivo = 0;
                $("input[type='checkbox']:checked").each(
                        function() {
                            vEstoquePositivo = 1;
                        }
                        );

                $("#modalBodyDadosRelatorio").load('/relatorio/relatorio-inventario-estoque', {
                    cdFornecedor: $("#cdFornecedor").val(),
                    cdTipoMercadoria: $("#cdTipoMercadoria").val(),                     estoquePositivo: vEstoquePositivo,
                    dtInicio: $("#dtInicio").val(),
                    dtTermino: $("#dtTermino").val(),
                    nrLivroPreco: $("#nrLivroPreco").val(),
                    stOrdem: $("input[type='radio'][name='rdbOrdenar']:checked").val()
                });
                $("#modalDadosRelatorio").modal('show');
                return false;
                }
            else
            {
            return true;
                }

        });

        $('#btnGerarPDF').click(function() {
            $("#pdf").val("true");
            $("#formRelatorio").submit();
        });


        $('#btnFechar').click(function() {
            $("#pdf").val("false");
            $("#modalDadosRelatorio").modal('hide');
        });

        $('#btnVoltarRelatorio').click(function() {
            window.location = '/relatorio/index';
        });
    });
</script>