<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <!--<i class="icon-check"></i>-->
                    <h3><?php echo "CADASTRO DE CONTAS A RECEBER" ?></h3>
                </div> <!-- /widget-header -->
                <form id="validation-form" action="<?php echo $form?>" method="post" role="form">

                    <div class="widget-content">

                    <div class="controls">
                        <div class="col-md-6">
                            <label class="text-info">Loja</label>
                            <input type="text" class="form-control" value="<?php echo $loja['ds_loja'] ?>" readonly="readonly"/>
                            <input type="hidden" id="CD_LOJA" name="CD_LOJA" class="form-control" value="<?php echo $loja['cd_loja'] ?>" />
                        </div>
                    </div>

                      <div class="controls">
                          <div class="col-md-6">
                              <label class="control-label text-info" for="name">Vendedor</label>
                              <select name="CD_FUNCIONARIO" id="CD_FUNCIONARIO" class="form-control">
                                  <option value="">Selecione...</option>
                                  <?php if($listaFuncionario):?>
                                      <?php foreach ($listaFuncionario as $funcionario):?>
                                          <option value="<?php  echo $funcionario['CD_FUNCIONARIO'];?>"<?php if($post['CD_FUNCIONARIO'] == $funcionario['CD_FUNCIONARIO'] ) echo  'selected="selected"' ?>>
                                              <?php echo $funcionario['DS_FUNCIONARIO'] ?>
                                          </option>
                                      <?php endforeach ?>
                                  <?php endif ?>
                              </select>
                          </div>
                      </div>
                      <br>

                        <div class="controls" >

                            <div class="col-md-1">
                                <label>Código</label>
                                <div class="input-group">
                                    <input type="number" name="codCliente" id="codCliente" class="form-control" min="1" max="9999999999" value="<?php echo $post['CD_CLIENTE'] ?>" />
                                </div>
                            </div>

                            <div class="col-md-1">
                                <label class="control-label text-info" for="name">&nbsp;</label><br>
                                <button type="button" id="searchCliente" class="form-control">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>

                            <div class="col-md-9">
                                <label class="control-label text-info" for="name">Nome / Razão Social:</label><br>
                                <input name="destNome" id="destNome" class="form-control"  maxlength="150" value="<?php echo utf8_encode($ds_cliente->ds_nome_razao_social) ?>" readonly />
                            </div>


                            <div class="col-md-1">
                                <label class="control-label text-info" for="name">&nbsp;</label><br>
                                <button type="button" class="form-control" id="cadastraClienteCompleto"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                        <div class="col-sm-12">&nbsp;</div>

                        <div class="controls">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="name">Número NF</label>
                                <input id="NR_NOTA" name="NR_NOTA" class="form-control" value="<?php echo $post['NR_NOTA']?>" maxlength="7" />
                            </div>
                            <div class="col-md-2">
                                <label class="control-label text-info" for="name">Número Doc</label>
                                <input id="NR_DOCUMENTO_CR" name="NR_DOCUMENTO_CR" class="dataP form-control" value="<?php echo $post['NR_DOCUMENTO_CR']?>" maxlength="10" />
                            </div>
                        </div>
                        <br>

                        <?php
                        $dataFormatadaEmissao = "";
                        $dataFormatadaVencimento = "";
                        $dataFormatadaMovimento = "";

                        if(!empty($post['DT_MOVIMENTO'])) {
                            $dtMov = new DateTime($post['DT_MOVIMENTO']);
                            $dataFormatadaMovimento = $dtMov->format('d-m-Y');
                        }

                        if(!empty($post['DT_EMISSAO'])) {
                            $dtEmissao = new DateTime($post['DT_EMISSAO']);
                            $dataFormatadaEmissao = $dtEmissao->format('d-m-Y');
                        }

                        if(!empty($post['DT_VENCIMENTO'])) {
                            $dtVencime = new DateTime($post['DT_VENCIMENTO']);
                            $dataFormatadaVencimento = $dtVencime->format('d-m-Y');
                        }

                        ?>

                        <div class="controls">
                          <div class="col-md-2">
                              <label class="control-label text-info" for="name">Data Movimentação</label>
                              <input id="DT_MOVIMENTO" name="DT_MOVIMENTO" class="dataP form-control" type="text" value="<?php echo $dataFormatadaMovimento ?>" maxlength="10" />
                          </div>
                          <div class="col-md-2">
                              <label class="control-label text-info" for="name">Data Emissão</label>
                              <input id="DT_EMISSAO" name="DT_EMISSAO" class="dataP form-control" type="text" value="<?php echo $dataFormatadaEmissao ?>" maxlength="10" />
                          </div>
                      </div>

                      <div class="controls">
                        <div class="col-md-2">
                            <label class="control-label text-info" for="name">Data Vencimento</label>
                            <input id="DT_VENCIMENTO" name="DT_VENCIMENTO" class="dataP form-control" type="text"  value="<?php echo $dataFormatadaVencimento ?>" maxlength="10" />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label text-info" for="name">Valor</label>
                            <input id="VL_DOCUMENTO" name="VL_DOCUMENTO" class="moeda form-control" value="<?php echo ($post['VL_DOCUMENTO']) ? number_format($post['VL_DOCUMENTO'],2) : "" ?>" maxlength="10" />
                        </div>
                        </div>
                        <div class="controls">
                            <div class="col-md-6">
                                <label class="control-label text-info" for="name">Classificação Financeira</label>
                                <select name="CD_CLASSE_FINANCEIRA" id="CD_CLASSE_FINANCEIRA" class="form-control">
                                    <?php if($listaClassificacao):?>
                                        <?php foreach ($listaClassificacao as $field => $value):?>
                                            <option value="<?php echo $field?>"
                                                <?php if($post['CD_CLASSE_FINANCEIRA'] == $field ) echo  'selected="selected"' ?> >
                                                <?php echo utf8_encode($value) ?>
                                            </option>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </select>
                            </div>
                        </div>
                        <div class="controls">
                            <div class="col-md-6">
                                <label class="control-label text-info" for="name">Centro de Custos</label>
                                <select name="CD_CENTRO_CUSTO" id="CD_CENTRO_CUSTO" class="form-control">
                                    <option value="0">Selecione...</option>
                                    <?php if($listaCentro):?>
                                        <?php foreach ($listaCentro as $centro):?>
                                            <option value="<?php echo $centro['CD_CENTRO_CUSTO'] ?>"
                                                <?php if($post['CD_CENTRO_CUSTO'] == $centro['CD_CENTRO_CUSTO'] ) echo  'selected="selected"' ?> >
                                                <?php echo utf8_encode($centro['DS_CENTRO_CUSTO']) ?>
                                            </option>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </select>
                            </div>
                        </div>
                        <div class="controls">
                            <div class="col-md-6">
                                <label class="control-label text-info" for="ds_fone1">Complemento</label>
                                <input name="DS_COMPL_HISTORICO" id="DS_COMPL_HISTORICO" class="form-control" value="<?php echo $post['DS_COMPL_HISTORICO']?>" maxlength="50"/>
                            </div>
                        </div>
                        <div class="controls">
                            <div class="col-md-6">
                                <label class="control-label text-info" for="ds_fone1">Observação</label>
                                <input name="DS_OBSERVACAO" id="DS_OBSERVACAO" class="form-control" value="<?php echo $post['DS_OBSERVACAO']?>" maxlength="100"/>
                            </div>
                        </div>

                        <div class="controls">
                            <div class="col-md-4">
                                <label class="control-label text-info" for="name">Tipo de pagamento</label>
                                <select name="CD_TIPO_PAGAMENTO" id="CD_TIPO_PAGAMENTO" class="form-control" required="true">
                                    <option value="">Selecione...</option>
                                    <?php if($listaPagamento):?>
                                        <?php foreach ($listaPagamento as $pagamento):?>
                                            <option value="<?php echo $pagamento['CD_TIPO_PAGAMENTO'] ?>"
                                                <?php if($post['CD_TIPO_PAGAMENTO'] == $pagamento['CD_TIPO_PAGAMENTO'] ) echo  'selected="selected"' ?> >
                                                <?php echo utf8_encode($pagamento['DS_TIPO_PAGAMENTO']) ?>
                                            </option>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </select>
                            </div>
                        </div>

                     <!--   <div class="controls" id="nome_emissor">
                            <div class="col-md-4">
                                <label class="control-label text-info" for="ds_fone1">Nome do Emissor</label>
                                <input name="DS_EMISSOR" id="DS_EMISSOR" class="form-control" value="<?php /*echo $post['DS_EMISSOR']*/?>" maxlength="50"/>
                            </div>
                        </div>

                        <div class="controls" id="CPF_emissor">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="ds_fone1">CPF/CNPJ Emissor</label>
                                <input type="number" name="NR_CGC_CPF_EMISSOR" id="CPF_EMISSOR" class="form-control" required="true" value="<?php /*echo $post['NR_CGC_CPF_EMISSOR']*/?>" required="true" maxlength="14"/>
                            </div>
                        </div>-->



                        <div class="controls" id="nome_emissor">
                            <div class="col-md-5">
                                <label class="control-label text-info" for="DS_EMISSOR">Nome do Emissor</label><br>
                                <input name="DS_EMISSOR" id="DS_EMISSOR" class="form-control"  maxlength="150" value="<?php echo $post['DS_EMISSOR'] ?>"  maxlength="50" />
                            </div>

                            <div class="controls" id="CPF_emissor">
                                <div class="col-md-2">
                                    <label class="control-label text-info" for="NR_CGC_CPF_EMISSOR">CPF/CNPJ Emissor</label>
                                    <input type="number" name="NR_CGC_CPF_EMISSOR" id="CPF_EMISSOR" class="form-control" required="true" value="<?php echo $post['NR_CGC_CPF_EMISSOR'] ?>" required="true" maxlength="14"/>
                                </div>
                            </div>

                            <div class="col-md-1">
                                <label class="control-label text-info" for="name">&nbsp;</label><br>
                                <button type="button" id="searchEmissor" class="form-control">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>


                        <div class="controls" id="foneEmissor" style="display: none;">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="ds_fone1">Fone Emissor</label>
                                <input name="NR_FONE_EMISSOR" id="NR_FONE_EMISSOR" class="form-control" value="<?php echo $post['NR_FONE_EMISSOR']?>" maxlength="12"/>
                            </div>
                        </div>
                        <div class="controls" id="banco_emissor" style="display: none;">
                            <div class="col-md-6">
                                <label class="control-label text-info" for="ds_fone1">Banco</label>
                                <select class="form-control" id="CD_BANCO" name="CD_BANCO">
                                    <option value="">Selecione...</option>
                                    <?php if($listaBancos):?>
                                        <?php foreach($listaBancos as $banco):?>
                                            <option value="<?php echo $banco['CD_BANCO']?>">
                                                <?php echo $banco['DS_BANCO']?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div class="controls" id="agencia_emissor" style="display: none;">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="ds_fone1">Agencia</label>
                                <input name="CD_AGENCIA" id="CD_AGENCIA" class="form-control" value="<?php echo $post['CD_AGENCIA']?>" maxlength="6"/>
                            </div>
                        </div>
                        <div class="controls" id="conta_emissor" style="display: none;">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="ds_fone1">Conta</label>
                                <input name="NR_CONTA" id="NR_CONTA" class="form-control" value="<?php echo $post['NR_CONTA']?>" maxlength="10"/>
                            </div>
                        </div>
                        <div class="controls" id="cheque_emissor" style="display: none;">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="ds_fone1">Cheque</label>
                                <input name="NR_CHEQUE" id="NR_CHEQUE" class="form-control" value="<?php echo $post['NR_CHEQUE']?>" maxlength="15"/>
                            </div>
                        </div>
                        <div class="controls" id="cartao_emissor" style="display: none;">
                            <div class="col-md-2">
                                <label class="control-label text-info" for="ds_fone1">Cartão</label>
                                <select class="form-control" id="CD_CARTAO" name="CD_CARTAO">
                                    <option value="">Selecione...</option>
                                    <?php if($listaCartao):?>
                                        <?php foreach($listaCartao as $cartao):?>
                                            <option value="<?php echo $cartao['CD_CARTAO']?>">
                                                <?php echo $cartao['DS_CARTAO']?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>

                        <div class="controls">
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="btn-group btn-group col-sm-12">
                                <div class="btn-group">
                                    <a href="/contas-receber"><button id="btn_voltar" type="button" class="btn btn-default voltar">
                                        <i class="i i-back"></i>
                                        Voltar
                                    </button></a>
                                </div>
                                <div class="btn-group">
                                    <button type="submit" class="btn btn-primary salvar">
                                        <i class="i i-success"></i>
                                        Salvar
                                    </button>
                                </div>
                            </div>
                            <br />
                        </div>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- Modal Pesquisa Cliente -->
<div id="pesquisaClienteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisaClienteModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <i class="icon-search icon-white"></i>
                <span class="text-info-modal">PESQUISA CLIENTE</span>
            </div>
            <div id="bodyPesquisaCliente" class="modal-body-xlarge"></div>
        </div>
    </div>
</div>

<!-- Modal Pesquisa Emissor -->
<div id="pesquisaEmissorModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisaEmissorModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <i class="icon-search icon-white"></i>
                <span class="text-info-modal">PESQUISA EMISSOR</span>
            </div>
            <div id="bodyPesquisaEmissor" class="modal-body-xlarge"></div>
        </div>
    </div>
</div>

<!-- Modal Cadastra Cliente -->
<div id="cadastraClienteCompletoModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cadastraClienteCompletoModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <i class="icon-search icon-white"></i>
                <span class="text-info-modal">Cadastrar Cliente</span>
            </div>
            <div id="bodyCadastroCliente" class="modal-body-xlarge"></div>
        </div>
    </div>
</div>

<style type="text/css">
    /* Input textbox - do not specify a width here, it will be overwritten */
    .ffb-input
    {
        float:left;
        color:#000; /* must specify along with watermark color */
        /*height:40px;  required for webkit browsers (Safari, Chrome) */
    }
    /* Color of watermark, if present */
    .ffb-input.watermark { /* added and removed dynamically */
        color:#888; /* must specify along with input color */
    }
    /* Drop-down arrow, with sprited image */
    .ffb-arrow
    {
        float:left;
        width:17px;
        height:22px;
        background-image:url(../img/sel_win7.gif);
    }
    .ffb-arrow.out { /* css sprite technique */
        background-position:0;
    }
    .ffb-arrow.over { /* css sprite technique */
        background-position:-17px 0;
    }
    .ffb-arrow.active { /* css sprite technique */
        background-position:-4px 0;
    }
    .ffb-no-results
    {
        padding:2px;
        color:#888;
        font-style:italic;
        border-bottom:1px solid #828790;
    }
    /* Container for dropdown contents */
    .ffb {
        position:absolute; /* this guy's parent div is hard-coded to position:relative */
        overflow:hidden;
        border-left:1px solid #828790; /* #7B9EBD for Vista */
        border-right:1px solid #828790;
        background-color:#fff; /* Give it a background-color, so it's not transparent */
    }
    /* Inner div for dropdown */
    .ffb .content {
        overflow:auto;
    }
    .ffb .content .row {
        border-bottom:1px solid #828790;
        color:#000;
        height:20px;
        clear:both;
    }
    .ffb-sel {
        cursor:pointer;
        cursor:hand;
        color:#fff !important;
        background-color:#39f;
    }
    .ffb-match {
        font-weight:bold;
        padding-left:32px;
        color:#000;
    }

    /* Paging */
    .ffb .paging {
        vertical-align:middle;
        border-bottom:1px solid #828790;
    }
    .ffb .page, .ffb a.page {
        font-size:85%;
        padding:2px;
        border:solid 1px #339;
        background-color:#eef;
        margin:2px;
    }
    .ffb .box {
        width:35px;
        margin:2px;
    }
    .ffb .summary {
        font-size:85%;
    }
</style>
<script>

    $(document).ready(function() {
        $('#DT_MOVIMENTO').datepicker({format: 'dd-mm-yyyy',
            language: 'pt-BR',
            todayBtn: "linked"});
        $('#DT_EMISSAO').datepicker({format: 'dd-mm-yyyy',
            language: 'pt-BR',
            todayBtn: "linked"});
        $('#DT_VENCIMENTO').datepicker({format: 'dd-mm-yyyy',
            language: 'pt-BR',
            todayBtn: "linked"});

        $(".autocomplete").flexbox('/contas-receber/buscarcliente', {
            queryDelay: 800,
            minChars: 3,
            paging: {
                pageSize: 5,
                summaryTemplate: 'Exibindo {start}-{end} de {total} registros'
            },
            //                        watermark: 'Informe o nome do cliente',
            hiddenValue: 'name',
            initialValue: '<?php echo $razao; ?>',
            onSelect: function() {

            }
        });

        $('#ds_nome_razao_social_input').attr('type', 'text');
        $('#ds_nome_razao_social_input').attr('class', 'form-control');
        $('#ds_nome_razao_social_input').attr('style', 'width: 100%;');
        $('#ds_nome_razao_social_input').attr('required', 'true');

        $('#CD_TIPO_PAGAMENTO').click(function() {
            if (this.value == 1 || this.value == "")
            {
                $('#nome_emissor').hide();
                $('#foneEmissor').hide();
                $('#CPF_emissor').show();
                $('#banco_emissor').hide();
                $('#agencia_emissor').hide();
                $('#conta_emissor').hide();
                $('#cheque_emissor').hide();
                $('#cartao_emissor').hide();
            } else if (this.value == 2) {
                $('#nome_emissor').show();
                $('#foneEmissor').show();
                $('#CPF_emissor').show();
                $('#banco_emissor').show();
                $('#agencia_emissor').show();
                $('#conta_emissor').show();
                $('#cheque_emissor').show();
                $('#cartao_emissor').hide();
            } if(this.value == 5) {
                $('#nome_emissor').show();
                $('#foneEmissor').show();
                $('#CPF_emissor').show();
                $('#banco_emissor').show();
                $('#agencia_emissor').show();
                $('#conta_emissor').show();
                $('#cheque_emissor').hide();
                $('#cartao_emissor').show();
            } else {
                $('#nome_emissor').show();
                $('#foneEmissor').hide();
                $('#CPF_emissor').show();
                $('#banco_emissor').hide();
                $('#agencia_emissor').hide();
                $('#conta_emissor').hide();
                $('#cheque_emissor').hide();
                $('#cartao_emissor').hide();
            }
        });

        $(".moeda").maskMoney({showSymbol:false, symbol:"", decimal:",", thousands:"."});

        $("#codCliente").change(function (){
            var cdCliente = $("#codCliente").val();

            if (cdCliente > 0){
                $.ajax({
                    type: 'post',
                    dataType: "json",
                    url: '/cliente/recupera-cliente-por-codigo',
                    data: {
                        cd_cliente: cdCliente
                    },
                    success: function(data) {
                        if (data.result == 'erro') {
                            alert(data.message);
                            $("#destNome").val("");
                            return false;
                        }

                        $("#destNome").val(data.data.ds_nome_razao_social);
                        $("#codCliente").val(data.data.cd_cliente);
                        $('.modal').modal('hide');
                    }
                });
            }
        });
    });

</script>
