<script type="text/javascript" src="/js/orangeweb/nota/nota.js"></script>
<? foreach( $config as $dado ) : ?>
<? foreach( $nfe as $nota ) : ?>
	<form class="form-horizontal"  id="nota" action="/nota/gera-nfe" method="post" role="form" enctype="multipart/form-data">
		<section class="panel panel-default">
			<div class="main">
				<div class="row-fluid">
					<div class="panel-body">
						<!-- Nav tabs -->
						<ul class="nav nav-tabs" role="tablist">
							<li role="presentation" class="active"><a href="#destinatario" aria-controls="destinatario" role="tab" data-toggle="tab">Nota Fiscal</a></li>
							<li role="presentation"><a href="#dadosNota" aria-controls="dadosNota" role="tab" data-toggle="tab">Dados da Nota</a></li>
							<li role="presentation"><a href="#retencao" aria-controls="retencao" role="tab" data-toggle="tab">Retenções</a></li>
							<!--<li role="presentation"><a href="#transporte" aria-controls="transporte" role="tab" data-toggle="tab">Transporte</a></li>-->
						</ul>
						<!-- Tab panes -->
						<div class="tab-content">
							<div role="tabpanel" class="tab-pane" id="dadosNota">
								<fieldset>
									<legend>Dados da Nota</legend>
									<div class="col-md-2">
										<label class="control-label text-info">Número de Nota:</label><br>
										<input type="text" value="<?php echo ( @$replicar == '1' ? '' : @$nota['infNFE'] )?>" name="infNFE" id="infNFE" class="form-control" readonly />
									</div>
									<div class="col-md-1">
										<label class="control-label text-info">Tipo:</label><br>
										<input type="radio" value="55" name="mod" <?php if($dado['DS_NOTA_PADRAO'] == 'NFE ') echo "checked" ?>>NFe
									</div>
									<div class="col-md-1">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="radio" value="65" name="mod" <?php if($dado['DS_NOTA_PADRAO'] == 'NFCE') echo "checked" ?> disabled>NFCe
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">Finalidade da Nota</label><br>
										<input type="radio" value="1" name="finNFe" Checked>Normal
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="radio" value="2" name="finNFe">Complementar
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="radio" value="3" name="finNFe">Ajuste
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="radio" value="4" name="finNFe">Devoluçao
									</div>
									<div class="col-md-12">&nbsp;</div>
									<div class="col-md-2">
										<label class="control-label text-info">Autorização:</label><br>
										<input type="text" value="<?php echo ( @$replicar == '1' ? '' : @$nota['DS_PROTOCOLO'] )?>" name="DS_PROTOCOLO" id="DS_PROTOCOLO" class="form-control" readonly />
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">Forma de Pagamento:</label><br>
										<input type="radio" value="0" name="indPag" <?php if($dado['CD_FORMA_PAGAMENTO'] == '0') echo "checked" ?>>À Vista
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="radio" value="1" name="indPag" <?php if($dado['CD_FORMA_PAGAMENTO'] == '1') echo "checked" ?>>Prazo
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="radio" value="2" name="indPag" <?php if($dado['CD_FORMA_PAGAMENTO'] == '2') echo "checked" ?>>Outros
									</div>
									<div class="col-md-4">
										<label class="control-label text-info">Data de Emissão / Data Saída:</label><br>
										<input class="form-control" type="date" name="dhEmi" id="dhEmi" value="<?php echo ( @$nota['dhEmi'] ? date('Y-m-d', $nota['dhEmi']) : date('Y-m-d'))?>" />
									</div>
									<div class="col-md-12">&nbsp;</div>
									<div class="col-md-7">
										<label class="control-label text-info">Natureza da operação:</label><br>
										<select class="form-control" name="natOp" id="natOp">
											<option>Selecione</option>
											<?php foreach( $cfop as $res ): ?>
												<option value="<?php echo $res['CD_NATUREZA_OPERACAO']?>" <?php if($res['CD_NATUREZA_OPERACAO'] == $dado['CD_NATUREZA_OPERACAO']) echo "selected"?>><?php echo utf8_encode($res['CD_NATUREZA_OPERACAO']." - ".$res['DS_NATUREZA_OPERACAO']) ?></option>
											<?php endforeach; ?>
										</select>
									</div>
									<div class="col-md-2">
										<label class="control-label text-info">CFOP:</label><br>
										<input type="hidden" name="xNatOp" id="xNatOp" />
										<input type="text" name="cfop" id="cfop" class="form-control" value="<?php echo ( @$nota['CFOP'] ? @$nota['CFOP'] : $dado['CD_NATUREZA_OPERACAO'] ) ?>"/>
									</div>
									<div class="col-md-3">
										<label class="control-label text-info">&nbsp;&nbsp;</label><br>
										<input type="checkbox" name="copiarCFOP">Copiar para serviços
									</div>
									<div class="col-md-12">&nbsp;</div>
									<div class="col-md-12">
										<label class="control-label text-info">Informações Adicionais:</label><br>
										<textarea name="infadc" id="infadc" class="form-control" rows="6"><?php echo @$nota['infCpl'] ?></textarea>
									</div>
									<div class="col-md-12">&nbsp;</div>
								</fieldset>
								<!--------------------------------------------------------------------------------------------------------------------->
							</div>
							<div role="tabpanel" class="tab-pane active" id="destinatario">
								<fieldset>
									<legend>Destinatário</legend>
									<div class="controls" >
										<div class="col-md-7">
											<label class="control-label text-info" for="name">Nome / Razão Social:</label><br>
											<!--<div id="ds_nome_razao_social" class="autocomplete"></div>-->
											<input name="destNome" id="destNome" class="form-control"  maxlength="255" value="<?php echo utf8_decode(@$nota['Dest_xNome']) ?>"/>
										</div>

										<div class="col-md-3">
											<label class="control-label text-info" for="name">CPF / CNPJ:</label><br>
											<input name="destCNPJ" id="destCNPJ" class="form-control"  maxlength="14" readonly value="<?php echo @$nota['Dest_CNPJCPF'] ?>" />
											<input type="hidden" name="codCliente" id="codCliente" value="<?php echo @$nota['CD_CLIENTE'] ?>" />
										</div>
										<div class="col-md-1">
											<label class="control-label text-info" for="name">&nbsp;</label><br>
											<button type="button" id="searchCliente" class="form-control">
												<i class="fa fa-search"></i>
											</button>
										</div>
										<div class="col-md-1">
											<label class="control-label text-info" for="name">&nbsp;</label><br>
											<button type="button" class="form-control" id="cadastraClienteCompleto"><i class="fa fa-plus"></i></button>
										</div>
									</div>
									<div class="col-sm-12">&nbsp;</div>
								</fieldset>
								<fieldset>
									<legend>Produtos</legend>
									<input type="hidden" name="nrPedido" id="nrPedido" value="<?php echo $nrPedido ?>" />
									<input type="hidden" name="tpPedido" id="tpPedido" value="<?php echo $tpPedido ?>" />
									<div class="row-fluid">
											<div class="col-md-1">
												<label>Código</label>
												<div class="input-group">
													<input type="text" name="CD_MERCADORIA" id="CD_MERCADORIA" class="form-control" value=""/>
												</div>
											</div>
											<div class="col-md-1">
												<label class="control-label text-info" for="name">&nbsp;</label><br>
												<button id="searchMercadoria" type="button" class="form-control">
													<i class="fa fa-search"></i>
												</button>
											</div>
											<div class="col-md-3">
												<label>Descrição</label><br>
												<input type="text" class="form-control" id="ds_mercadoria" name="ds_mercadoria" maxlength="120" />
											</div>
											<div class="col-md-2">
												<label>Valor Unitário</label><br>
												<input type="text" class="form-control" id="vl_preco_unitario" name="vl_preco_unitario" onKeyUp="moeda(this)" />
											</div>
											<div class="col-md-1">
												<label>Qtd</label><br>
												<input type="text" class="form-control" value="1" id="qtd_mercadoria" name="qtd_mercadoria" />
												<!-- <input type="text" class="form-control" value="1" id="qtd_mercadoria" name="qtd_mercadoria" onKeyUp="moeda(this)"  /> -->
											</div>
											<div class="col-md-2">
												<label>Total</label><br>
												<input type="text" class="form-control" id="vl_tot" name="vl_tot" readonly />
											</div>
											<div class="col-md-2">
												<label>&nbsp;</label><br>
												<button id="btnIncluirMercadoria" class="btn btn-primary" type="button"><i class="icon-white icon-plus"></i>&nbsp;Adicionar a nota</button>
											</div>
											<div class="col-md-12">&nbsp;</div>
										<div class="col-md-12">&nbsp;</div>
										<div class="col-md-12">
											<table class="table table-striped table-bordered" id="tabelaMercadorias" name="tabelaMercadorias">
												<thead>
													<tr>
														<th>
															<button type="button" id="chkTodos" class="btn btn-info" ><i class="icon-white"></i></button>
														</th>
														<th>
															<span><?php echo "PRODUTO / SERVIÇO" ?></span>
														</th>
														<th>
															<span>Quantidade</span>
														</th>
														<th>
															<span>Valor Unitario</span>
														</th>
														<th>
															<span>Total</span>
														</th>
													</tr>
												</thead>
												<tbody>
												<?php if( @$nfeMerc ) :?>
												<?php foreach( $nfeMerc as $merc ): ?>
												<tr>
													<td>
														<button type="button" name="chkMercadoria[]" id="chkMercadoria<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo $merc['CD_MERCADORIA'] ?>" class="btn btn-info" onclick="verificaStatus($(this))"><i class=\"icon-white\"></i></button>
														<input type="hidden" name="cdMercadoria[]" value="<?php echo $merc['CD_MERCADORIA'] ?>" />
													</td>
													<td>
														<?php echo $merc['xProd'] ?> <input type="hidden" name="ds_mercadoria-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo $merc['xProd'] ?>" />
													</td>
													<td>
														<?php echo $merc['qCom'] ?> <input type="hidden" name="qtdVendida-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo $merc['qCom'] ?>" />
													</td>
													<td>
														<?php echo $merc['vUnCom'] ?> <input type="hidden" name="vl_preco_unitario-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo number_format($merc['vUnCom'],2, '.', '') ?>" />
													</td>
													<td>
														<?php echo $merc['vProd'] ?> <input type="hidden" name="vl_tot-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo number_format($merc['vProd'],2, '.', '') ?>" />
													</td>
												</tr>
												<?php endforeach; ?>
												<?php endif; ?>
												</tbody>
											</table>
										</div>
									</div>
									<div class="fluid">
										<button id="btnExcluirMercadoria" class="btn  btn-info span3 pull-left" type="button"><i class="icon-white icon-trash"></i>&nbsp;Excluir selecionados</button>
										<input type="text" class="btn  btn-info span3 pull-right" readonly value="<?php echo ( @$totalNota ? number_format($totalNota, 2, ',', '.') : 0.00 )?>" id="totalNota">
									</div>
									<div class="col-md-12">&nbsp;</div>

								</fieldset>
								<!-------------------------------------------------------------------------------------->
							</div>
							<div role="tabpanel" class="tab-pane" id="retencao">
								<div class="controls" >
									<div class="col-sm-12 col-md-12">
										<div class="col-md-3">
											<label class="control-label text-info" for="name">BC PIS:</label><br>
											<input name="retPis_bc" id="retPis_bc" class="form-control" onKeyUp="moeda(this)" value="<?php echo (@$nota['RET_Base_PIS'] ? number_format( @$nota['RET_Base_PIS'], 2, ',', '.') : 0) ?>"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Aliq PIS(%):</label><br>
											<input name="retPis_aliq" id="retPis_aliq" class="form-control"  value="<?php echo ( @$nota['RET_Aliq_PIS'] ? number_format( @$nota['RET_Base_PIS'], 2) : number_format($dado['RETENCAO_pPIS'],2) )?>" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Total PIS:</label><br>
											<input name="retPis_total" id="retPis_total" class="form-control" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info"></label><br>
											<input type="checkbox" value="1" name="retPis" <?php echo ( @$nota['RET_Base_PIS'] > 0 ? 'checked' : '' ) ?>>Habilitar
										</div>
										<div class="col-sm-12 col-md-12">&nbsp;</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">BC COFINS:</label><br>
											<input name="retCofins_bc" id="retCofins_bc" class="form-control" onKeyUp="moeda(this)" value="<?php echo ( @$nota['RET_Base_COFINS'] ? number_format( @$nota['RET_Base_COFINS'], 2, ',', '.') : 0 ) ?>"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Aliq COFINS(%):</label><br>
											<input name="retCofins_aliq" id="retCofins_aliq" class="form-control"  value="<?php echo number_format($dado['RETENCAO_pCOFINS'],2)?>" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Total COFINS:</label><br>
											<input name="retCofins_total" id="retCofins_total" class="form-control" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info"></label><br>
											<input type="checkbox" value="1" name="retCofins" <?php echo ( @$nota['RET_Base_COFINS'] > 0 ? 'checked' : '' ) ?>>Habilitar
										</div>
										<div class="col-sm-12 col-md-12">&nbsp;</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">BC CSLL:</label><br>
											<input name="retCsll_bc" id="retCsll_bc" class="form-control" onKeyUp="moeda(this)" value="<?php echo ( @$nota['RET_Base_CSLL'] ? number_format( @$nota['RET_Base_CSLL'], 2, ',', '.') : 0 ) ?>"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Aliq CSLL(%):</label><br>
											<input name="retCsll_aliq" id="retCsll_aliq" class="form-control" value="<?php echo number_format($dado['RETENCAO_pCSLL'],2)?>" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Total CSLL:</label><br>
											<input name="retCsll_total" id="retCsll_total" class="form-control" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info"></label><br>
											<input type="checkbox" value="1" name="retCsll" <?php echo ( @$nota['RET_Base_CSLL'] > 0 ? 'checked' : '' ) ?>>Habilitar
										</div>
										<div class="col-sm-12 col-md-12">&nbsp;</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">BC IRRF:</label><br>
											<input name="retIrrf_bc" id="retIrrf_bc" class="form-control" onKeyUp="moeda(this)" value="<?php echo ( @$nota['RET_Base_IRRF'] ? number_format( @$nota['RET_Base_IRRF'], 2, ',', '.') : 0 ) ?>"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Aliq IRRF(%):</label><br>
											<input name="retIrrf_aliq" id="retIrrf_aliq" class="form-control" value="<?php echo number_format($dado['RETENCAO_pIRRF'],2)?>" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Total IRRF:</label><br>
											<input name="retIrrf_total" id="retIrrf_total" class="form-control" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info"></label><br>
											<input type="checkbox" value="1" name="retIrrf" <?php echo ( @$nota['RET_Base_IRRF'] > 0 ? 'checked' : '' ) ?>>Habilitar
										</div>
										<div class="col-sm-12 col-md-12">&nbsp;</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">BC Previdência:</label><br>
											<input name="retPrev_bc" id="retPrev_bc" class="form-control" onKeyUp="moeda(this)" value="<?php echo ( @$nota['RET_Base_PREV'] ?  number_format( @$nota['RET_Base_PREV'], 2, ',', '.') : 0 ) ?>" />
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Aliq Previdência(%):</label><br>
											<input name="retPrev_aliq" id="retPrev_aliq" class="form-control" value="<?php echo number_format($dado['RETENCAO_pPrevidencia'],2)?>" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info" for="name">Total Previdência:</label><br>
											<input name="retPrev_total" id="retPrev_total" class="form-control" onKeyUp="moeda(this)"/>
										</div>
										<div class="col-md-3">
											<label class="control-label text-info"></label><br>
											<input type="checkbox" value="1" name="retPrev" <?php echo ( @$nota['RET_Base_PREV'] > 0 ? 'checked' : '' ) ?>>Habilitar
										</div>
										<div class="col-sm-12 col-md-12">&nbsp;</div>
									</div>
								</div>
								<div class="col-sm-12 col-md-12">&nbsp;</div>
								<!------------------------------------------------------------------------------------------------------------------------------------->
							</div>
							<!--<div role="tabpanel" class="tab-pane" id="transporte">
								<fieldset>
									<legend>Transporte</legend>
									<div class="col-md-12">
										<label class="control-label text-info" for="name">Modalidade Frete:</label><br>
										<input type="radio" name="modFrete">&nbsp;Por conta do emitente<br>
										<input type="radio" name="modFrete">&nbsp;Por conta do distinatário/remetente<br>
										<input type="radio" name="modFrete">&nbsp;Por conta de terceiros<br>
										<input type="radio" name="modFrete" checked>&nbsp;Sem frete<br>
									</div>
									<div class="col-md-12">&nbsp;</div>
									<div class="col-md-3">
										<label class="control-label text-info" for="name">CNPJ/CPF</label><br>
										<input type="text" class="form-control" />
									</div>
									<div class="col-md-3">
										<label class="control-label text-info" for="name">Inscrição Estadual</label><br>
										<input type="text" class="form-control" />
									</div>
									<div class="col-md-6">
										<label class="control-label text-info" for="name">Razão Social ou nome transportadora</label><br>
										<input type="text" class="form-control" />
									</div>
									<div class="col-md-6">
										<label class="control-label text-info" for="name">Endereço completo</label><br>
										<input type="text" class="form-control" />
									</div>
									<div class="col-md-3">
										<label class="control-label text-info" for="name">Município</label><br>
										<input type="text" class="form-control" />
									</div>
									<div class="col-md-3">
										<label class="control-label text-info" for="name">UF</label><br>
										<input type="text" class="form-control" />
									</div>
								</fieldset>
							</div>

								<!------------------------------------------------------------------------------------------------------>
						</div>
					<div class="col-lg-12">
						<hr>
						<button id="btnEmitirNota" name="emitir" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Emitir</button>
						<button id="btnSalvarNota" name="save" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Salvar</button>
						<button id="btnCancelarRelatorio" class="btn btn-default btn" type="reset"><i class="icon-remove icon-white"></i>&nbsp;Limpar</button>
<!--						<button id="btnVoltarRelatorio"    class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button> </a>
-->
					</div>
					</div>
				</div>
			</div>
		</section>

		<!-- ###### MODAIS ###### -->

		<!-- Indicar Paciente -->
		<div id="pacientedMed" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pacientedMed" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">Indicar Paciente</span>
					</div>
					<div class="modal-body-xlarge">
						<div class="row-fluid">
							<div class="panel-body">
								<div class="col-md-8">
									<label>Nome: </label>
									<input type="text" class="form-control" id="nome_paciente" name="nome_paciente" id="nome_paciente" <?php if( $dado['ST_OBRIGA_PACIENTE'] == 'S' ) echo 'required' ?> />
								</div>
								<div class="col-md-4">
									<label>&nbsp;</label>
									<button type="button" id="btnCopiaDestDMED" class="form-control">Copiar Destinatário</button>
								</div>
								<div class="col-md-12">
									<label>CPF: </label>
									<input type="text" class="form-control" id="cpf_paciente" name="cpf_paciente" id="cpf_paciente" <?php if( $dado['ST_OBRIGA_PACIENTE'] == 'S' ) echo 'required' ?> />
								</div>
								<div class="col-md-12">
									<label>Data de Nascimento: </label>
									<input type="date" class="form-control" id="nascimento_paciente" name="nascimento_paciente" />
								</div>
								<div class="col-lg-12">
									<hr>
									<button id="btnEmitirNota" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Ok</button>
									<button id="btnVoltarRelatorio"    class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>

	<!-- Modal Pesquisa Cliente -->
		<div id="pesquisaClienteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisaClienteModal" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">PESQUISA CLIENTE</span>
					</div>
					<div id="bodyPesquisaCliente" class="modal-body-xlarge"></div>
				</div>
			</div>
		</div>
		<!-- Modal Pesquisa Mercadoria -->
		<div id="pesquisaMercadoriaModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisaMercadoriaModal" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">PESQUISA MERCADORIA - PREÇO DE VENDA</span>
					</div>
					<div id="bodyMercadoria" class="modal-body-xlarge"></div>
				</div>
			</div>
		</div>
		<!-- Modal Cadastra Cliente -->
		<div id="cadastraClienteCompletoModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cadastraClienteCompletoModal" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">Cadastrar Cliente</span>
					</div>
					<div id="bodyCadastroCliente" class="modal-body-xlarge"></div>
				</div>
			</div>
		</div>
	<script type="text/javascript">
		$(document).ready(function() {
			Nota.init();
			$("#btnEmitirNota").click(function () {
				if($("#destCNPJ").val() == ''){
					alert('Cliente sem cadastro de CPF/CNPJ');
					return false;
				}
			<?php if( $dado['ST_OBRIGA_PACIENTE'] == 'S' ){
				echo	'$("#pacientedMed").modal("show");';
			}?>
			});

			$('input').keypress(function (e) {
				var code = null;
				code = (e.keyCode ? e.keyCode : e.which);
				return (code == 13) ? false : true;
			});

			$('#infadc').keypress(function(event) {
			   if (event.keyCode == 13) {
						event.preventDefault();
					}
			});
		});
	</script>
<?php endforeach; ?>
<?php endforeach; ?>
<style type="text/css">
    /* Input textbox - do not specify a width here, it will be overwritten */
    .ffb-input
    {
        float:left;
        color:#000; /* must specify along with watermark color */
        /*height:40px;  required for webkit browsers (Safari, Chrome) */
    }
    /* Color of watermark, if present */
    .ffb-input.watermark { /* added and removed dynamically */
        color:#888; /* must specify along with input color */
    }
    /* Drop-down arrow, with sprited image */
    .ffb-arrow
    {
        float:left;
        width:17px;
        height:22px;
        background-image:url(../img/sel_win7.gif);
    }
    .ffb-arrow.out { /* css sprite technique */
        background-position:0;
    }
    .ffb-arrow.over { /* css sprite technique */
        background-position:-17px 0;
    }
    .ffb-arrow.active { /* css sprite technique */
        background-position:-4px 0;
    }
    .ffb-no-results
    {
        padding:2px;
        color:#888;
        font-style:italic;
        border-bottom:1px solid #828790;
    }
    /* Container for dropdown contents */
    .ffb {
        position:absolute; /* this guy's parent div is hard-coded to position:relative */
        overflow:hidden;
        border-left:1px solid #828790; /* #7B9EBD for Vista */
        border-right:1px solid #828790;
        background-color:#fff; /* Give it a background-color, so it's not transparent */
    }
    /* Inner div for dropdown */
    .ffb .content {
        overflow:auto;
    }
    .ffb .content .row {
        border-bottom:1px solid #828790;
        color:#000;
        height:20px;
        clear:both;
    }
    .ffb-sel {
        cursor:pointer;
        cursor:hand;
        color:#fff !important;
        background-color:#39f;
    }
    .ffb-match {
        font-weight:bold;
        padding-left:32px;
        color:#000;
    }

    /* Paging */
    .ffb .paging {
        vertical-align:middle;
        border-bottom:1px solid #828790;
    }
    .ffb .page, .ffb a.page {
        font-size:85%;
        padding:2px;
        border:solid 1px #339;
        background-color:#eef;
        margin:2px;
    }
    .ffb .box {
        width:22px;
        margin:2px;
    }
    .ffb .summary {
        font-size:85%;
    }
</style>
