<script type="text/javascript" src="/js/orangeweb/nota/nota.js"></script>
<section class="panel panel-default">
	<div class="main">
		<div class="row-fluid">
			<div class="panel-body">
				<div class="widget-header">
					<h3>Envio de NFe</h3>
				</div>
				<?php if( @$erro ): ?>
					<div class="col-sm-12">
						<h3>Nota não enviada!</h3>
						<h3><?php echo $erro; ?></h3>
						<a href="javascript:window.history.go(-1)">
							<button type="button" class="btn btn-primary">
								Voltar 
							</button>
						</a>
						<a href="/nota/lista">
							<button type="button" class="btn btn-default">
								Cancelar	
							</button>
						</a>
					</div>
				<?php else: ?>
					<?php if( @$retorno['prot']['0']['nProt'] == '' ): ?>
						<div class="col-sm-12">
							<h3>Nota não enviada!</h3>
							<h3><?php echo $retorno['prot']['0']['xMotivo']; ?></h3>							
							<a href="javascript:window.history.go(-1)">
								<button type="button" class="btn btn-primary"> 
									Voltar 
								</button>
							</a>
							<a href="/nota/lista">
								<button type="button" class="btn btn-default">
									Cancelar	
								</button>
							</a>
						</div>
					<?php else: ?>
						<div class="col-sm-12">
							<h3>Envio com sucesso!</h3>
							<a href="/nota/imprime-danfe?nCh=<?php echo $retorno['prot']['0']['chNFe'].'&data='.$data?>">
								<button type="button" class="btn btn-primary">
									Imprimir
								</button>
							</a>
							<a href="/nota/avulsa">
								<button type="button" class="btn btn-primary">
									Emitir outra 
								</button>
							</a>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			</div>
		</div>
	</div>
</section>
	