<script type="text/javascript" src="/js/orangeweb/nota/nota.js"></script>
<section class="panel panel-default">
	<div class="main">
		<div class="row-fluid">
			<div class="panel-body">
				<div class="widget-header">
					<h3>Envio de NFe/NFCe a partir do recebimento no caixa</h3>
				</div>
				<?php if( @$erro ): ?>
					<div class="col-sm-12">
						<h3 class="text-danger text-center">Nota não  enviada!</h3>
						<h4>
                            <?php echo $erro; ?>
                        </h4>

                        <a href="/caixa/index">
							<button type="button" class="btn btn-primary">
								Voltar
							</button>
						</a>
                        <a href="/nota/lista">
                            <button type="button" class="btn btn-primary">
                                Ir para a lista de notas
                            </button>
                        </a>
					</div>
				<?php else: ?>
					<?php if( @$retorno['prot']['0']['nProt'] == '' ): ?>
						<div class="col-sm-12">
                            <h3 class="text-danger text-center">Nota não enviada!</h3>
							<h4 class="text-center">
                                <?php echo $retorno['prot']['0']['xMotivo']; ?>
                            </h4>
                            <a href="/caixa/index">
								<button type="button" class="btn btn-primary"> 
									Voltar 
								</button>
							</a>
							<a href="/nota/lista">
								<button type="button" class="btn btn-primary">
                                    Ir para a lista de notas
								</button>
							</a>
						</div>
					<?php else: ?>
						<div class="col-sm-12">
							<h3 class="text-success text-center">Envio com sucesso!</h3>

                            <h4 class="text-center">
                                <?php echo $retorno['prot']['0']['xMotivo']; ?>
                            </h4>

                            <?php if($retornoMail) :?>
                                <h4 class="text-center">
                                  Nota enviada para:  <?php echo $emailsEnviados; ?>
                                </h4>
                            <?php endif; ?>

                            <a href="/caixa/index">
                                <button type="button" class="btn btn-primary">
                                    Voltar
                                </button>
                            </a>

                         <?php if ($mod == '55') : ?>
                            <a href="/nota/imprime-danfe?nCh=<?php echo $retorno['prot']['0']['chNFe'].'&data='.$data?>" target="_blank">
                         <?php else: ?>
                            <a href="/nota/imprime-danfce?nCh=<?php echo $retorno['prot']['0']['chNFe'].'&data='.$data?>" target="_blank">
                         <?php endif; ?>

                                <button type="button" class="btn btn-primary">
                                    Imprimir
                                </button>
                            </a>

                        <?php if ($mod == '65') : ?>
                            <a alt="Enviar por e-mail" href="#" data-toggle="tooltip" data-placement="top"
                               title="Enviar por e-mail " onclick='enviaNota("<?php echo $retorno['prot']['0']['chNFe']; ?>","<?php echo $data ?>","<?php echo $mod; ?>")'
                               data-original-title="Enviar nota por e-mail">
                                <button type="button" class="btn btn-primary">
                                    Enviar por email
                                </button>
                            </a>
                        <?php endif; ?>
						</div>
					<?php endif; ?>
				<?php endif; ?>

			</div>
		</div>
	</div>
<?php echo $this->partial('Application\nota\modal-email.phtml'); ?>