<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de Notas</h3>
                </div>	
            </div>
        </div>
		<?php
        if (@$success) {
            echo '<div class="alert alert-success">
                    <a class="close" data-dismiss="alert" href="#">x</a>' . $success . '
                  </div>';
        }
		if (@$error) {
            echo '<div class="alert alert-danger">
                    <a class="close" data-dismiss="alert" href="#">x</a>' . $error . '
                  </div>';
        }
        ?>
		<div class="row-fluid" id="result">  
            <div class="widget stacked" >
				<form class="form-horizontal" id="validation-form" novalidate="novalidate" method="post" role="form" action="/nota/lista">
					<div class="controls">
						<div class="col-sm-1">
							<label>Nº Nota</label>
							<input type="text" class="form-control" name="infNFE" id="infNFE" />
						</div>
						<div class="col-sm-4">
							<label>Chave Nota</label>
							<input type="text" class="form-control" name="DS_NFE_CHAVE" id="DS_NFE_CHAVE" />
						</div>
						<div class="col-sm-3">
							<label>Cliente</label>
							<input type="text" class="form-control" name="Dest_xNome" id="Dest_xNome" />
						</div>
						<div class="col-sm-2">
							<label>&nbsp;</label>
							<button type="submit" id="btnSubmit" class="btn btn-primary form-control">
                                <i class="fa fa-search"></i>
                                Pesquisar
                            </button>
						</div>
                        <div class="col-sm-2">
                            <label>&nbsp;</label>
                            <button id="btnNovaNota" type="button" class="btn btn-success form-control" >
                                <i class="i glyphicon-plus"></i>
                                Adicionar  nota
                            </button>
                        </div>
					</div>
				</form>
			</div>
		</div>
		<br><hr><br>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                            <tr >
                                <!-- th nowrap>#</th -->
                                <th nowrap>Nº Nota</th>
                                <th nowrap>Cliente</th>
                                <th nowrap>Data Emissão</th>
                                <th nowrap>Valor</th>
                                <th nowrap>Situação</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($listaNfe)) : ?>
                                <?php foreach ($listaNfe as $nfe): ?>
                                    <?php
                                        $foiInutilizada = in_array($nfe->infNFE,$listaNfeInutilizadas);
                                    ?>
                                    <tr>
                                        <!-- td align="right"><?php //echo $cliente->CD_CLIENTE  ?></td -->
                                        <td align="left"><?php echo $nfe->infNFE ?></td>
                                        <td align="left"><?php echo utf8_encode($nfe->Dest_xNome) ?></td>
                                        <td align="center">
                                        <?php
                                            if ($nfe->DT_PROTOCOLO_DATA == ''){
                                                echo '';
                                            } else {
                                                echo datE('d/m/y', strtotime($nfe['dEmi']));
                                            }
                                         ?>
                                        </td>
                                        <td align="right">
                                            <?php
                                              if ((float)$nfe['ICMSTot_vNF'] > 0) {
                                                  echo number_format($nfe['ICMSTot_vNF'],2);
                                              } else {
                                                  echo number_format($nfe['ISSQNtot_vServ'],2);
                                              }

                                            ?></td>
                                        <td align="left">
											<?php
                                                if ($foiInutilizada) {
                                                    echo 'Inutilizada';
                                                }else if( $nfe->DS_PROTOCOLO == ''){
                                                    echo 'Não enviada';
                                                } else {
                                                    if( $nfe->DS_CANCELA_PROTOCOLO == '' ){
                                                        echo 'Enviada';
                                                    }else{
                                                        echo 'Nota Cancelada';
                                                    }
                                                }
											?>
										</td>
										<td align="left">
                                         <!-- <a href="/mercadoria/editar?id=<?php echo $nfe->infNFe ?>" ><i class="fa fa-pencil"></i></a> <!--  |-->
										<?php if( $nfe->DS_PROTOCOLO && !$nfe->DS_CANCELA_PROTOCOLO && !$foiInutilizada): ?>
											<a alt="Abrir NFe" href="/nota/abrir?infNFe=<?php echo $nfe['infNFE'] ?>&replicar=1" data-toggle="tooltip" data-placement="top" title="Replicar NF-e"><i alt="Replicar NFe" class="fa fa-files-o"></i></a>
                                            &nbsp;|&nbsp;<a alt="Enviar por E-mail" href="#" data-toggle="tooltip" data-placement="top" title="Enviar nota por E-mail" onclick="enviaNota(<?php echo "'".$nfe->DS_NFE_CHAVE."','".date('Ym', strtotime($nfe->dEmi))."'"?>)"><span class="glyphicon glyphicon-envelope"></span></a>
                                            &nbsp;|&nbsp;<a alt="Imprimir NFe" href="/nota/imprime-danfe?nCh=<?php echo $nfe->DS_NFE_CHAVE.'&data='.date('Ym', strtotime($nfe->dEmi))?>"data-toggle="tooltip" data-placement="top" title="Imprimir NF-e"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;
                                             | <a alt="Carta de Correção CCe" href="#" data-toggle="tooltip" data-placement="top" title="Carta de Correção CCe" onclick="cce(<?php echo "'".$nfe->DS_NFE_CHAVE."'".','."'".$nfe->mod."'".','."'".$nfe->tpAmb."'" ?>)"><i class= "fa fa-eraser"></i></a>
											 | <a alt="Cancelar NFe" href="#" data-toggle="tooltip" data-placement="top" title="Cancelar NF-e" onclick="cancelaNota(<?php echo "'".$nfe->DS_NFE_CHAVE."'".','."'".$nfe->mod."'".','."'".$nfe->tpAmb."'".','."'".$nfe->DS_PROTOCOLO."'" ?>)"><i class="fa fa-times-circle"></i></a>
                                        <?php elseif(!$foiInutilizada): ?>
											<a alt="Visualizar NFe" target="_blank" href="/nota/visualiza-danfe?nCh=<?php echo $nfe->DS_NFE_CHAVE ?>" data-toggle="tooltip" data-placement="top" title="Pré-visualizar NF-e"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;
											<?php if( $nfe->DS_CANCELA_PROTOCOLO && !$foiInutilizada): ?>
                                                &nbsp;| <a alt="Abrir NFe" href="/nota/abrir?infNFe=<?php echo $nfe['infNFE']?>&replicar=1" ><i class="fa fa-files-o"></i></a>
											<?php else: ?>
                                                &nbsp;| <a alt="Abrir NFe" href="/nota/abrir?infNFe=<?php echo $nfe['infNFE'] ?>"data-toggle="tooltip" data-placement="top" title="Editar NF-e"><i class="fa fa-pencil"></i></a>
											<?php endif; ?>
										<?php endif; ?>
										</td>
                                        </th>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <!-- th nowrap>#</th -->
                                <th nowrap>Nº Nota</th>
                                <th nowrap>Cliente</th>
                                <th nowrap>Data Emissão</th>
                                <th nowrap>Valor</th>
                                <th nowrap>Situação</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </tfoot>
                    </table>
                    <?php echo $this->paginationControl($listaNfe, 'Sliding', 'partials/paginator/control.phtml') ?>
                	<br><hr><br>
					<div class="col-sm-12">
						<fieldset>
							<legend>Baixar XML / PDF :</legend>
							<form class="form-horizontal" id="saveNota" method="post" role="form" action="/nota/save-nota">
								<div class="col-sm-2">
                                    <label>Mês</label>
									<select class="form-control" name="mes" id="mes" required="required">
										<option value=''>Selecione</option>
										<option value='01'>Janeiro</option>
										<option value='02'>Fevereiro</option>
										<option value='03'>Março</option>
										<option value='04'>Abril</option>
										<option value='05'>Maio</option>
										<option value='06'>Junho</option>
										<option value='07'>Julho</option>
										<option value='08'>Agosto</option>
										<option value='09'>Setembro</option>
										<option value='10'>Outubro</option>
										<option value='11'>Novembro</option>
										<option value='12'>Dezembro</option>
									</select>
								</div>
								<div class="col-sm-2">
                                    <label>Ano</label>
									<select class="form-control" name="ano" id="ano" required="required">
										<option value=''>Selecione</option>
										<?php 
											for($i = date('Y') - 5; $i <= date('Y'); $i++ ){
												echo "<option value='$i'>$i</option>";
											}
										?>
									</select>
								</div>
								<div class="col-sm-2">
                                     <br/>
									&nbsp;<button type="submit" class="btn btn-success" >Baixar</button>
								</div>
							</form>
						</fieldset>
					</div>
				</div>
            </div>
        </div>
    </div>
	<!-- Modal cancelamentoi -->
		<div id="modalCancelamento" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCancelamento" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">Cancelar Nota</span>
					</div>
					<div class="modal-body-xlarge">
						<div class="row-fluid">
							<div class="panel-body">
								<form action="/nota/cancela" method="post">
									<div class="col-md-8">
										<label>Chave: </label>
										<input type="text" class="form-control" id="chave" name="chave" required readonly/>
									</div>
									<div class="col-md-12">
										<label>Jutificativa: </label>
										<input type="text" class="form-control" id="xJust" name="xJust" required />
									</div>
									<div class="col-lg-12">
										<hr>
										<input type="hidden" name="mod" id="mod" />
										<input type="hidden" name="tpAmb" id="tpAmb" />
										<input type="hidden" name="nProt" id="nProt" />
										<button id="btnCancelarNota" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Ok</button>
										<button id="btnVoltar"   type="button"  data-dismiss="modal"   class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Modal CartaCorreção -->
		<div id="modalCCe" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCCe" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">Carta de Correção</span>
					</div>
					<div class="modal-body-xlarge">
						<div class="row-fluid">
							<div class="panel-body">
								<form action="/nota/cartaCorrecao" method="post">
									<div class="col-md-8">
										<label>Chave: </label>
										<input type="text" class="form-control" id="chaveCCe" name="chaveCCe" required readonly/>
									</div>
									<div class="col-md-12">
										<label>Correção: </label>
										<input type="text" class="form-control" id="xCorrecao" name="xCorrecao" required />
									</div>
									<div class="col-lg-12">
										<hr>
										<input type="hidden" name="modCCe" id="modCCe" />
										<input type="hidden" name="tpAmbCCe" id="tpAmbCCe" />
										<button id="btnCCe" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Ok</button>
										<button id="btnVoltar"  type="button"  data-dismiss="modal"    class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	<!-- Modal email -->
		<div id="modalEmail" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalEmail" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">X</button>
						<i class="icon-search icon-white"></i>
						<span class="text-info-modal">Enviar Nota</span>
					</div>
					<div class="modal-body-xlarge">
						<div class="row-fluid">
							<div class="panel-body">
								<form action="/nota/send" method="post">
									<div class="col-md-8">
										<label>Chave: </label>
										<input type="text" class="form-control" id="chaveMail" name="chaveMail" required />
									</div>
									<div class="col-md-12">
										<label>Email: </label>
										<input type="text" class="form-control" id="email" name="email" required />
									</div>
									<div class="col-lg-12">
										<hr>
										<input type="hidden" name="mod" id="mod" />
										<input type="hidden" name="tpAmb" id="tpAmb" />
										<input type="hidden" name="nProt" id="nProt" />
										<input type="hidden" name="dataemis" id="dataemis" />
										<button id="btnCancelarNota" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Ok</button>
										<button id="btnVoltar"  type="button"  data-dismiss="modal" class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</section>
<script>
    $(document).ready(function() {

        $("#btnNovaNota").click(function() {
            window.location = "/nota/avulsa";
        });

    });

	function cancelaNota(chave, mod, tpAmb, nProt) {
		$('#chave').val(chave);
		$('#mod').val(mod);
		$('#tpAmb').val(tpAmb);
		$('#nProt').val(nProt);
        $('#modalCancelamento').modal('show');
    }
	
	function cce(chave, mod, tpAmb) {
		$('#chaveCCe').val(chave);
		$('#modCCe').val(mod);
		$('#tpAmbCCe').val(tpAmb);
        $('#modalCCe').modal('show');
    }
	
	function enviaNota(chave, dataemis) {
		$('#chaveMail').val(chave);
		$('#dataemis').val(dataemis);
        $('#modalEmail').modal('show');
    }
</script>