<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header fluid">
                    <i class="icon-check"></i>
                    <h3>Estoque</h3>
                </div>
                <div class="widget-content">
                    <!--
                            <a  class="btn btn-info btn-block" href="/relatorio/atendimento">Relat&oacute;rio de Tipo de Atendimento</a><br />
                            <a  class="btn btn-info btn-block" href="/relatorio/caixa">Relat&oacute;rio de Caixa</a><br />
                            <a  class="btn btn-info btn-block" href="/relatorio/resumo-caixa">Relat&oacute;rio do Resumo de Caixa</a><br />
                    -->
                    <div class="widget-content">

                        <!-- LEFT -->
                        <div class="col-lg-4">
                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Movimentação
                                </header>
                                <div class="list-group bg-white">
                                    <a href="/estoque/movimentacao" class="list-group-item">
                                        Controle de entrada e saída de Estoque
                                    </a>
                                </div>
                            </section>
                        </div>

                        <!-- CENTER -->
                        <div class="col-lg-4">

                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Mercadoria
                                </header>
                                <div class="list-group bg-white">
                                    <a href="" class="list-group-item">
                                        Controle de Mercadorias
                                    </a>
                                </div>
                            </section>
                        </div>



                        <div class="clear"></div>
                        <br>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>