<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <!--<i class="icon-check"></i>-->
                    <h3><?php echo utf8_encode("Baixa de Parcelas") ?></h3>
                </div> <!-- /widget-header -->
                <form id="validation-form" action="<?php echo $form?>" method="post" role="form">
                    <div class="widget-content">

                        <div class="controls">
                            <div class="col-md-3">
                                <label class="control-label text-info" for="name">Data Baixa</label>
                                <input id="DT_BAIXA" name="DT_BAIXA" class="dataP form-control" value="<?php $date = new DateTime($post['DT_BAIXA']); echo $date->format('d-m-y');?>" maxlength="10" />
                            </div>
                        </div>

                        <div class="controls">
                            <div class="col-md-6">
                                <label class="control-label text-info" for="ds_fone1">Banco para Pagamento</label>
                                <select class="form-control" id="CD_BANCO_PAGAMENTO" name="CD_BANCO_PAGAMENTO">
                                    <option value="">Selecione...</option>
                                    <?php if($listaBancos):?>
                                        <?php foreach($listaBancos as $banco):?>
                                            <option value="<?php echo $banco['CD_CONTA']?>"
                                                <?php if($post['CD_CONTA'] == $banco['CD_CONTA']) echo "selected='selected'" ?>>
                                                <?php echo $banco['DS_BANCO'].' - '.$banco['DS_AGENCIA']?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label class="control-label text-info" for="name">Número Cheque</label>
                            <input id="NR_CHEQUE" name="NR_CHEQUE" class="form-control" value="<?php echo $post['NR_CHEQUE']?>" />
                        </div>

                        <div class="col-md-3">
                            <label class="control-label text-info" for="name">Valor Parcela</label>
                            <input id="VL_DOCUMETO" name="VL_DOCUMENTO" class="form-control" value="<?php echo number_format($post['VL_DOCUMENTO'],2,",",".") ?>" />
                        </div>

                        <div class="col-md-2">
                            <label class="control-label text-info" for="name">Valor Desconto</label>
                            <input id="VL_DESCONTO" name="VL_DESCONTO" class="form-control" value="<?php echo number_format($post['VL_DESCONTO'],2,",",".") ?>" />
                        </div>

                        <div class="col-md-2">
                            <label class="control-label text-info" for="name">Valor Multa</label>
                            <input id="VL_MULTA" name="VL_MULTA" class="form-control" value="<?php echo number_format($post['VL_MULTA'],2,",",".") ?>" />
                        </div>

                        <div class="col-md-2">
                            <label class="control-label text-info" for="name">Valor Juros</label>
                            <input id="VL_JUROS" name="VL_JUROS" class="form-control" value="<?php echo number_format($post['VL_JUROS'],2,",",".") ?>" />
                        </div>

                        <div class="col-md-3">
                            <label class="control-label text-info" for="name">Valor Pagamento</label>
                            <input id="VL_PAGAMENTO" name="VL_PAGAMENTO" class="form-control" value="<?php echo number_format($post['VL_PAGAMENTO'],2,",",".") ?>" DISABLED/>
                        </div>

                        <div class="controls">
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="btn-group btn-group col-sm-12">
                                <!--<div class="btn-group">
                                    <a href="/contas-pagar"><button id="btn_voltar" type="button" class="btn btn-default voltar">
                                            <i class="i i-back"></i>
                                            Voltar
                                        </button></a>
                                </div>-->
                                <div class="btn-group">
                                    <button type="submit" class="btn btn-primary salvar">
                                        <i class="i i-success"></i>
                                        Baixar
                                    </button>
                                </div>
                            </div>
                            <br />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>