<section class="panel panel-default">
<div class="main">
<div class="row-fluid">
<div class="panel-body">
<div class="widget-header">
    <h3>Contas a Pagar</h3>
</div>
<div class="widget-content">
    <div class="widget-content">

        <form class="form-horizontal" id="validation-form" action="/contas-pagar/pesquisa" novalidate="novalidate" method="post" role="form">

            <div class="controls">
                <div class="col-md-12">
                    <label class="text-info">Loja</label>
                    <input type="text" class="form-control" value="<?php echo $loja['ds_loja'] ?>" readonly="readonly"/>
                    <input type="hidden" id="CD_LOJA" name="CD_LOJA" class="form-control" value="<?php echo $loja['cd_loja'] ?>" />
                </div>
            </div>
            <br>

            <div class="controls">
                <div class="col-md-6">
                    <label class="control-label text-info" for="name">Tipo de pagamento</label>
                    <select name="CD_TIPO_PAGAMENTO" id="CD_TIPO_PAGAMENTO" class="form-control">
                        <option value="">Selecione...</option>
                        <?php if($listaPagamento):?>
                            <?php foreach ($listaPagamento as $pagamento):?>
                                <option value="<?php echo $pagamento['CD_TIPO_PAGAMENTO'] ?>"
                                    <?php if($pagamento['CD_TIPO_PAGAMENTO'] == $post['CD_TIPO_PAGAMENTO']) echo 'selected="selected"' ?>>
                                    <?php echo utf8_encode($pagamento['DS_TIPO_PAGAMENTO']) ?>
                                </option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="controls">
                <div class="col-md-3">
                    <label class="control-label text-info" for="name">Número Documento</label>
                    <input id="DS_DOCUMENTO" name="DS_DOCUMENTO" class="form-control" value="<?php echo $post['DS_DOCUMENTO']?>" maxlength="10" />
                </div>
                <div class="col-md-3">
                    <label class="control-label text-info" for="name">Valor Doc</label>
                    <input id="VL_DOCUMENTO" name="VL_DOCUMENTO" class="form-control" value="<?php echo $post['VL_DOCUMENTO']?>" maxlength="10" />
                </div>
            </div>
            <br>

            <div class="controls">
                <div class="col-md-6">
                    <label class="control-label text-info" for="name">Fornecedor</label>
                    <select name="CD_FORNECEDOR" id="CD_FORNECEDOR" class="form-control">
                        <option value="">Selecione...</option>
                        <?php if($listaFornecedor):?>
                            <?php foreach ($listaFornecedor as $fornecedor):?>
                                <option value="<?php echo $fornecedor['CD_FORNECEDOR'] ?>"
                                    <?php if($pagamento['CD_FORNECEDOR'] == $post['CD_FORNECEDOR']) echo 'selected="selected"' ?>>
                                    <?php echo utf8_encode($fornecedor['DS_RAZAO_SOCIAL']) ?>
                                </option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="controls">
                <div class="col-md-6">
                    <label class="control-label text-info" for="nr_cgc_cpf"><?php echo utf8_encode("CREDOR") ?></label>
                    <input name="DS_CREDOR" id="DS_CREDOR" class="form-control" value="<?php echo $post['DS_CREDOR']?>" maxlength="255"/>
                </div>
            </div>
            <BR>

            <div class="controls">
                <div class="col-md-3">
                    <label class="control-label text-info" for="name">Faixa de Valores</label>
                    <input id="minValor" name="minValor" class="form-control" value="<?php echo $post['minValor']?>" maxlength="10" />
                </div>
                <div class="col-md-3">
                    <label class="control-label text-info" for="name">&nbsp;</label>
                    <input id="maxValor" name="maxValor" class="form-control" value="<?php echo $post['maxValor']?>" maxlength="10" />
                </div>
            </div>

            <div class="controls">
                <div class="col-md-3">
                    <label class="control-label text-info" for="name">Perído de Vencimento</label>
                    <input id="dtIni" name="dtIni" class="dataP form-control" value="<?php echo $post['dtIni']?>" maxlength="10" />
                </div>
                <div class="col-md-3">
                    <label class="control-label text-info" for="name">&nbsp;</label>
                    <input id="dtFim" name="dtFim" class="dataP form-control" value="<?php echo $post['dtFim']?>" maxlength="10" />
                </div>
            </div>

            <div class="controls">
                <div class="col-sm-12">&nbsp;</div>
                <div class="btn-group btn-group col-sm-12">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default voltar">
                            <i class="i i-back"></i>
                            Limpar
                        </button>
                    </div>
                    <div class="btn-group">
                        <button type="submit" id="btnSubmit" class="btn btn-primary pesquisar">
                            <i class="i i-search"></i>
                            Pesquisar
                        </button>
                    </div>
                </div>
                <br />
            </div>
        </form>
            <div class="row-fluid" id="result">
                <div class="widget stacked" >
                    <div class="controls">
                        <div class="col-sm-12">
                            <button id="btnNovo" class="btn btn-success" style="float:right; margin-top:5px; margin-right:5px;">
                                <i class="icon-plus icon-white"></i>
                                + Adicionar
                            </button>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped m-b-none" data-ride="datatables">
                            <thead>
                            <tr >
                                <th nowrap>Doc/Pedido</th>
                                <th nowrap>Fornecedor / Credor</th>
                                <th nowrap>Data</th>
                                <th nowrap>Valor do Documento</th>
                                <th nowrap>Opcao</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($contasPagar)) :?>
                                <?php foreach ($contasPagar as $pagar):?>
                                    <tr>
                                        <td><?php echo $pagar->DS_DOCUMENTO ?></td>
                                        <td><?php echo (empty($pagar->DS_RAZAO_SOCIAL )) ? $pagar->DS_CREDOR : $pagar->DS_RAZAO_SOCIAL  ?></td>
                                        <td><?php  $date = new DateTime($pagar->DT_MOVIMENTO); echo $date->format('d-m-y'); ?> </td>
                                        <td><?php echo number_format($pagar->VL_DOCUMENTO,2,",",".") ?></td>
                                        <td> <a href="/contas-pagar/editar?id=<?php echo $pagar->NR_DOCUMENTO_CP ?>" ><i class="fa fa-pencil"></i></a> <!--  |
                                            <a href="/cliente/remover?id=<?php echo $pagar->NR_DOCUMENTO_CP ?>" ><i class="fa fa-trash-o"></i></a>-->
                                        </td>
                                        </th>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th nowrap>Doc/Pedido</th>
                                <th nowrap>Fornecedor / Credor</th>
                                <th nowrap>Data</th>
                                <th nowrap>Valor do Documento</th>
                                <th nowrap>Opcao</th>
                            </tr>
                            </tfoot>
                        </table>
                        <?php if($contasPagar) echo $this->paginationControl($contasPagar, 'Sliding', 'partials/paginator/control.phtml') ?>

                    </div>
                </div>
            </div>
    </div>
</div>
</div>
</div>
</div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $("#btnNovo").click(function() {
            window.location = "/contas-receber/cadastrar";
        });
        $('.voltar').click(function() {
            $('#CD_TIPO_PAGAMENTO').val('');
            $('#DS_DOCUMENTO').val('');
            $('#VL_DOCUMENTO').val('');
            $('#CD_FORNECEDOR').val('');
            $('#DS_CREDOR').val('');
            $('#minValor').val('');
            $('#maxValor').val('');
            $('#dtIni').val('');
            $('#dtFim').val('');
        });
        $('#dtIni').datepicker({format: 'dd-mm-yyyy',
            language: 'pt-BR',
            todayBtn: "linked"});
        $('#dtFim').datepicker({format: 'dd-mm-yyyy',
            language: 'pt-BR',
            todayBtn: "linked"});
        $("#btnNovo").click(function() {
            window.location = "/contas-pagar/cadastrar";});
    });
</script>
