<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="col-md-12"></div>

                <div class="controls">
                    <div class="controls">

                        <div class="col-md-12">
                            <span class="text-danger">Alerta: </span>
                        </div>
                        <div class="col-md-12">
                            <span class="text-danger">Para emissão do modelo 55 (NF-e) é obrigatorio informar o CPF/CNPJ de cliente um já cadastrado!</span>
                        </div>
                        <div class="col-md-12">
                            <span class="text-danger">Para emissão sem o CPF/CNPJ do cliente, somente o modelo 65 é habilitado.</span>
                        </div>

                        <div class="col-md-12">&nbsp;</div>
                        <div class="col-md-12">&nbsp;</div>

                        <div class="col-md-6">
                            <label class="text-info">Informe o CPF / CNPJ: </label>
                            <input type="hidden" name="modEmissaoCpfNota"  id="modEmissaoCpfNota" value="<?php echo $modEmissaoCpfNota ?>"/>
                            <input type="text" class="form-control" name="cpfcnpjEmissao" id="cpfcnpjEmissao"
                                   value="<?php echo $cliente['nr_cgc_cpf'] ?>" placeholder="Digite o número a ser impresso na nota fiscal"
                                    name='cpfcnpjEmissao' maxlength="18" onblur="validaDuplicidade(this.value)"/>
                        </div>

                        <div class="col-md-12">&nbsp;</div>

                    </div>
                </div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
                <div class="col-md-12">&nbsp;</div>
            </div>
            <div class="panel-footer">
                <div class="controls">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary" id="prosseguirModalCpfNota">
                            <i class="i i-ok"></i>
                            Prosseguir
                        </button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-danger" id="cancelarModalCpfNota">
                            <i class="i i-cancel"></i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {

        $('#prosseguirModalCpfNota').click(function() {
           var  nrCpfCnpj       = $.trim($("#cpfcnpjEmissao").val());
                nrCpfCnpj       = nrCpfCnpj.replace(/[-/\\^$*+?.()|[\]{}]/g, '');
           var  mod             = $("#modEmissaoCpfNota").val();
           var  nrCpfCnpjValido = true;

           //valida
            if (nrCpfCnpj != '') {
                nrCpfCnpjValido = validarCpfCnpj(nrCpfCnpj) ;

                if (nrCpfCnpjValido) {
                    // se houver cpf/cnpj valido e existente na base de dados
                    validaExistenciaCpfCnpj(nrCpfCnpj);
                    return;
                } else {
                    alert('Favor informar um "CPF / CNPJ" válido!!!');
                    return;
                }
            } else {
                if (mod == '55') {
                    alert('Para emissão do modelo 55 (NF-e) é obrigatorio informar o CPF/CNPJ de um cliente já cadastrado!');
                    return;
                } else {
                    // se não houver cpf/cnpj  emitir cupom fiscal prossegue para o recebimento e emissão da nota fiscal
                    prosseguir()
                }
            }

        });

        $('#cancelarModalCpfNota').click(function() {
            $('#bodyDivModalCpfNota').html('');
            $('#divModalCpfNota').modal('hide');
        });

        // trigger keypress
        $("#cpfcnpjEmissao").keypress(function(){
            v =  $(this).val();
            //Remove tudo o que não é dígito
            v =v.replace(/\D/g,"");

            if (v.length <= 14) { //CPF

                return formatar('###.###.###-##',this,true,event);

            } else { //CNPJ

                return formatar('##.###.###/####-##',this,true,event);

            }

        });


        validarCpfCnpj = function(nrCpfCnpj) {

            if ((nrCpfCnpj.length < 11) ||
                        ( nrCpfCnpj.length > 11 && nrCpfCnpj.length < 14)) {
                return false;
            } else {
                return true;
            }
        }

        validaExistenciaCpfCnpj =   function (doc) {


            if( doc != "") {
                $.ajax({
                    url: "/cliente/valida-duplicidade",
                    type: "POST",
                    dataType: "json",
                    cache : "false",
                    data: {
                        nr_cgc_cpf: doc
                    },
                    success: function(data) {
                        if (data.retorno == "S") {
                            alert('CPF / CNPJ  de número ' + doc + ' não existe entre os clientes cadastrados!');
                            $("#cpfcnpjEmissao").val("");
                        }else {
                            $("#destCpfCnpj").val( $("#cpfcnpjEmissao").val());
                            prosseguir();
                        }
                    }
                });
            }


        }



    });

</script>