<div class="controls">
    <div class="col-md-2">
        <label>Código</label>
        <select class="form-control">
            <option value="">Default select</option>
        </select>
    </div>
    <div class="col-md-3">
        <label>Descrição</label>
        <input type="input" class="form-control"/>
    </div>
    <div class="col-md-2">
        <label>Retirada</label>
        <input type="input" class="form-control"/>
    </div>
    <div class="col-md-1">
        <label>Qtd.</label>
        <input type="input" class="form-control"/>
    </div>
    <div class="col-md-1">
        <label>% Desc.</label>
        <input type="input" class="form-control"/>
    </div>
    <div class="col-md-2">
        <label>Pço Unitário</label>
        <input type="input" class="form-control"/>
    </div>
    <div class="col-md-1">
        <label>&nbsp;</label>
        <div>
            <i class="i i-add-to-list"></i>
        </div>
    </div>
</div>

<div class="table-responsive">
    <br />
    <table class="table table-hover">
        <thead>
        <td>CÓDIGO</td>
        <td>DESCRIÇÃO DA MERCADORIA</td>
        <td>QTD</td>
        <td>DESC. (%)</td>
        <td>VALOR DESC.</td>
        <td>VALOR NOMINAL</td>
        <td>VALOR TOTAL</td>
        <td>V. C.</td>
        <td>PROMOÇÃO</td>
        <td>ENTREGA</td>
        </thead>
        <tbody>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        </tbody>
    </table>
</div>