<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Pedido de Venda</h3>
                    <div class="controls">
                        <span><i class="icon-check"></i>&nbsp;Pedidos em aberto</span>
                    </div>
                    <div class="controls" style="text-align: right;">
						<a href="/pedido/novo-pedido"><button id="btnNovoPedido" class="btn btn-info right" style="">
                            <i class="icon-refresh icon-white"></i>
                            &nbsp; Novo Pedido
                        </button></a>
						<button id="btnAtualizarLista" class="btn btn-danger right" style="">
                            <i class="icon-refresh icon-white"></i>
                            &nbsp; Atualizar lista
                        </button>
                    </div>
                </div>
                <div class="widget-content">

                    <div class="controls">
                        <table class="table table-striped  table-hover" id="tableGridPedidos">
                            <thead>
                                <tr >
                                    <th nowrap>Pedido</th>
                                    <th nowrap>Nome Cliente</th>
                                    <th nowrap>Valor</th>
                                    <th nowrap>Vendedor</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th nowrap>Pedido</th>
                                    <th nowrap>Nome Cliente</th>
                                    <th nowrap>Valor</th>
                                    <th nowrap>Vendedor</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--  <tr class="linkPedido" data-idPedido="<?php //echo $pedido["NR_PEDIDO"]      ?>" data-idLoja="<?php //echo $pedido["CD_LOJA"]      ?>"></tr>-->
<div id="modalPedidoTablet" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalPedidoTablet" aria-hidden="true">

    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <span class="text-info-modal"><i class="icon-white icon-check"></i> Pedido Tablet</span>
            </div>
            <div id="modalBodyPedidoTablet" class="container-fluid"></div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {

        /* Table initialisation */
        oTableLista = $('#tableGridPedidos').dataTable({
            //"sDom": "<'row'<'span8'l><'span8'f>r>t<'row'<'span8'i><'span8'p>>",

            "sPaginationType": "bootstrap",
            "oLanguage": {"sLenghtMenu": "_MENU_ registros por pag."},
            //"sScrollY": "280px",
            "bScrollCollapse": true,
            "bPaginate": true,
            "bLengthChange": false,
            "iDisplayLength": 10,
            "bFilter": false,
            "bInfo": false,
            "bProcessing": true,
            "bServerSide": false,
            "sAjaxSource": "/pedido/grid-lista",
            "aoColumns": [
                {"sClass": "nowrap left", "sWidth": "5%"},
                {"sClass": "nowrap left", "sWidth": "45%"},
                {"sClass": "nowrap left", "sWidth": "20%"},
                {"sClass": "nowrap left", "sWidth": "30%"},
                {"sClass": "nowrap left", "sWidth": "1%", "bVisible": false},
                {"sClass": "nowrap left", "sWidth": "1%", "bVisible": false},
                {"sClass": "nowrap left", "sWidth": "1%", "bVisible": false}
            ]

        });

        $('#tableGridPedidos').on("click", "tr", function(event) {

            $("#modalBodyPedidoTablet").load('/pedido/pedido-tablet', {
                nrPedido: oTableLista.fnGetData(this)[0],
                nmCliente: oTableLista.fnGetData(this)[1],
                cdVendedor: oTableLista.fnGetData(this)[4],
                nrLoja: oTableLista.fnGetData(this)[5],
                tpPedido: oTableLista.fnGetData(this)[6]});
            $("#modalPedidoTablet").modal('show');
        });


        $("#btnAtualizarLista").click(function() {
            oTableLista.fnReloadAjax();
        });
    });
</script>