<?php if (count($this->flashMessenger()->getMessages())) : ?>
    <?php
    foreach ($this->flashMessenger()->getMessages() as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<script type="text/javascript" src="/js/orangeweb/pedido/pedido.js"></script>
<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Pedido de Venda</h3>
                    <div class="controls">
                        <span><i class="icon-check"></i>&nbsp;Pedidos em aberto</span>
                    </div>
                    <div class="controls" style="text-align: right;">
                        <button id="btnNovoPedido" class="btn btn-success right" style="">
                            <i class="i glyphicon-plus"></i>
                            &nbsp; Novo Pedido
                        </button>
						<button id="btnAtualizarLista" class="btn btn-primary right" style="">
                            <i class="i i-history"></i>
                            &nbsp; Atualizar lista
                        </button>
                    </div>
                </div>
                <div class="widget-content">

                    <div class="controls">
                        <table class="table table-striped  table-hover" id="tableGridPedidos">
                            <thead>
                                <tr >
                                    <th nowrap>Pedido</th>
                                    <th nowrap>Nome Cliente</th>
                                    <th nowrap>Valor</th>
                                    <th nowrap>Vendedor</th>
                                    <th nowrap>Data do pedido</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th>A&ccedil;&otilde;es</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th nowrap>Pedido</th>
                                    <th nowrap>Nome Cliente</th>
                                    <th nowrap>Valor</th>
                                    <th nowrap>Vendedor</th>
                                    <th nowrap>Data do pedido</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th>A&ccedil;&otilde;es</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function() {

        /* Table initialisation */
        oTableLista = $('#tableGridPedidos').dataTable({
            "sDom": "<'row'<'span8'l><'span8'f>r>t<'row'<'span8'i><'span8'p>>",
            "aaSorting": [[ 4, "asc" ]],
            "sPaginationType": "full_numbers",
            "oLanguage": {"sLenghtMenu": "_MENU_ registros por pag."},
            //"sScrollY": "280px",
            "bScrollCollapse": true,
            "bPaginate": true,
            "bLengthChange": false,
            "iDisplayLength": 15,
            "bFilter": false,
            "bInfo": false,
            "bProcessing": true,
            "bServerSide": false,
            "sAjaxSource": "/pedido/grid-lista",
            "aoColumns": [
                {"sClass": "nowrap left", "sWidth": "5%"},
                {"sClass": "nowrap left", "sWidth": "40%"},
                {"sClass": "nowrap text-right", "sWidth": "15%"},
                {"sClass": "nowrap left", "sWidth": "20%"},
                {"sClass": "nowrap text-center", "sWidth": "20%"},
                {"sClass": "nowrap left", "sWidth": "1%", "bVisible": false},
                {"sClass": "nowrap left", "sWidth": "1%", "bVisible": false},
                {"sClass": "nowrap left", "sWidth": "1%", "bVisible": false},
                {"sClass": "nowrap center", "sWidth": "1%"},
            ]

        });

        $('#btnNovoPedido').click(function() {
            window.location = "/pedido/novo-pedido";
        });


        $("#btnAtualizarLista").click(function() {
            oTableLista.fnReloadAjax();
        });
    });
</script>