<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="controls">
                    <div class="col-md-3">
                        <label class="text-info">Pesquisar por</label>
                        <select class="form-control" name="" id="">
                            <option value="">Código da Lista</option>
                            <option value="">Série/Característica</option>
                            <option value="">Código da Empresa</option>
                            <option value="">Nome da Empresa</option>
                            <option value="">Endereço da Empresa</option>
                            <option value="">Cidade da Empresa</option>
                            <option value="">Código do Funcionário</option>
                            <option value="">Nome do Funcionário</option>
                        </select>
                    </div>
                </div>
                <div class="controls">
                    <div class="col-md-4">
                        <label class="text-info">Procurar por</label>
                        <input type="text" class="form-control" name="" id="" value="" />
                    </div>
                </div>
                <div class="controls">
                    <div class="col-md-2">
                        <label class="text-info">&nbsp;</label>
                        <div>
                            <button type="button" class="btn btn-info" id="btnPesquisaMercadoria">
                                <i class="i i-search"></i>
                                Localizar
                            </button>
                        </div>
                    </div>
                </div>
                <div class="controls">
                    <div class="col-md-3">
                        <label class="text-info">&nbsp;</label>
                        <div>
                            <input type="checkbox" />
                            Mostrar Listas Excluídas
                        </div>
                    </div>
                </div>
                <div class="col-md-12"></div>
                <div class="controls" style=" width: 98%; overflow-x: scroll;">
                    <div class="table-responsive">
                        <br />
                        <table class="table table-hover">
                            <thead>
                            <td>LOJA</td>
                            <td>NOME DA LOJA</td>
                            <td>LISTA</td>
                            <td>NOME DA LISTA</td>
                            <td>SÉRIE/CARACT.</td>
                            <td>EMPRESA</td>
                            <td>NOME DA EMPRESA</td>
                            <td>ENDEREÇO DA EMPRESA</td>
                            <td>CIDADE DA EMPRESA</td>
                            <td>UF EMPRESA</td>
                            <td>CÓD. FUNC.</td>
                            <td>FUNCIONÁRIO RESPONSÁVEL</td>
                            <td>OBSERVAÇÃO</td>
                            </thead>
                            <tbody>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="13">Total de Registro(s): </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="controls">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary concluir">
                            <i class="i i-ok"></i>
                            Ok
                        </button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default cancelar">
                            <i class="i i-cancel"></i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#btnPesquisaMercadoria').click(function() {
            $('#bodyBuscarLista').html('');
            $('#bodyBuscarLista').load('/pedido/modal-pesquisa-lista-mercadoria');
            $('#buscarListaModal').modal('show');
        });
    });
</script>