<script type="text/javascript" src="/js/orangeweb/pedido/pedido.js"></script>

<form class="form-horizontal"  id="pedido" action="/pedido/salvar-novo-pedido" method="post" role="form" enctype="multipart/form-data">

    <input type="hidden" name="tpPedido" id="tpPedido" value="P" />
    <input type="hidden" name="cdTpPedido" id="cdTpPedido" value="<?php echo @$pedido['CD_TIPO_PEDIDO'] ?>" />
    <input type="hidden" name="flRedirecionarAoCaixa" id="flRedirecionarAoCaixa" value="N" />


    <section class="panel panel-default">
        <div class="main">
            <div class="row-fluid">
                <div class="panel-body">
                    <!-- Nav tabs -->
<!--                    <ul class="nav nav-tabs" role="tablist">-->
<!--                        <li role="presentation" class="active"><a href="#destinatario" aria-controls="destinatario" role="tab" data-toggle="tab">Pedido</a></li>-->
<!--                        <li role="presentation"><a href="#dadosPedido" aria-controls="dadosPedido" role="tab" data-toggle="tab">Dados do Pedido</a></li>-->
<!--                    </ul>-->
                    <!-- Tab panes -->
                    <div class="tab-content">
<!--                        <div role="tabpanel" class="tab-pane active" id="destinatario">-->
                            <fieldset>
                                <legend>Dados do Pedido</legend>
                                <div class="col-md-2">
                                    <label class="control-label text-info">Número do Pedido:</label>
                                    <input type="text" value="<?php echo $pedido['NR_PEDIDO'] ?>" name="nrPedido" id="nrPedido" class="form-control" readonly />
                                </div>
                                <div class="col-md-2">
                                    <label class="control-label text-info">Data do Pedido:</label>
                                    <input type="text" class="dataP form-control" name="dtPedido" id="dtPedido" value="<?php echo ( @$pedido['DT_PEDIDO'] ? date(FORMATO_ESCRITA_DATA, strtotime($pedido['DT_PEDIDO'])) : date('d-m-Y'))?>" required />
                                </div>

                                <div class="controls col-md-4">
                                    <label for="validateSelectProfissional" class="control-label text-info" >&nbsp;Vendedor:</label>
                                    <select name="cdVendedor" id="cdVendedor" class="form-control" onchange="desabilitaAlerta()" required>
                                        <option value="">Selecione...</option>
                                        <?php
                                        foreach ($vendedores as $vendedor) {
                                            $selected = "  ";
                                            if ((int) $vendedor["CD_FUNCIONARIO"] == (int) $pedido['CD_FUNCIONARIO']) {
                                                $selected = " selected ";
                                            }
                                            echo "<option value='{$vendedor["CD_FUNCIONARIO"]}'  " . $selected . ">{$vendedor["CD_FUNCIONARIO"]} - " . utf8_encode($vendedor["DS_FUNCIONARIO"]) . "</option>";
                                        }
                                        ?>
                                    </select>
                                </div>
                                <div class="col-sm-12">&nbsp;</div>
                            </fieldset>
                            <!--------------------------------------------------------------------------------------------------------------------->
                            <fieldset>
                                <legend>Cliente</legend>
                                <div class="controls" >

                                    <div class="col-md-1">
                                        <label>Código</label>
                                        <div class="input-group">
                                            <input type="number" name="codCliente" id="codCliente" class="form-control" min="1" max="9999999999" value="<?php echo @$pedido['CD_CLIENTE'] ?>" />
                                        </div>
                                    </div>

                                    <div class="col-md-1">
                                        <label class="control-label text-info" for="name">&nbsp;</label><br>
                                        <button type="button" id="searchCliente" class="form-control">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>

                                    <div class="col-md-6">
                                        <label class="control-label text-info" for="name">Nome / Razão Social:</label>
                                        <input name="destNome" id="destNome" class="form-control"  maxlength="255" value="<?php echo @$cliente['ds_nome_razao_social'] ?>" required  readonly />
                                    </div>

                                    <div class="col-md-3">
                                        <label class="control-label text-info" for="name">CPF / CNPJ:</label><br>
                                        <input name="destCNPJ" id="destCNPJ" class="form-control"  maxlength="14" readonly value="<?php echo @$cliente['nr_cgc_cpf'] ?>" readonly />

                                    </div>

                                    <div class="col-md-1">
                                        <label class="control-label text-info" for="name">&nbsp;</label><br>
                                        <button type="button" class="form-control" id="cadastraClienteCompleto"><i class="fa fa-plus"></i></button>
                                    </div>


                                </div>
                                <div class="col-sm-12">&nbsp;</div>
                            </fieldset>
                            <fieldset>
                                <legend>Produtos</legend>

                                <input type="hidden" name="isServico" id="isServico" value="<?php echo @$pedidoMerc[0]['ST_SERVICO']; ?>" />
                                <input type="hidden" name="isServicoProxProduto" id="isServicoProxProduto" value="" />
                                <div class="row-fluid">
                                    <div class="col-md-1">
                                        <label>Código</label>
                                        <div class="input-group">
                                            <input type="number" name="CD_MERCADORIA" id="CD_MERCADORIA" class="form-control" value="" min="1" max="9999999999"/>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <label class="control-label text-info" for="name">&nbsp;</label><br>
                                        <button id="searchMercadoria" type="button" class="form-control">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                    <div class="col-md-5">
                                        <label>Descrição</label><br>
                                        <input type="text" class="form-control" id="ds_mercadoria" name="ds_mercadoria" maxlength="120" readonly/>
                                    </div>
                                    <div class="col-md-2">
                                        <label>Valor Unitário</label><br>
                                        <input type="text" class="form-control" id="vl_preco_unitario" name="vl_preco_unitario" onKeyUp="moeda(this)" />
                                    </div>
                                    <div class="col-md-1">
                                        <label>Qtd</label><br>
                                        <input type="text" class="form-control numbersOnly" value="1" id="qtd_mercadoria" name="qtd_mercadoria" />
                                    </div>
                                    <div class="col-md-2">
                                        <label>Total</label><br>
                                        <input type="text" class="form-control" id="vl_tot" name="vl_tot" readonly />
                                    </div>
                                    <div class="col-md-12">
                                        <label>&nbsp;</label><br>
                                        <button id="btnIncluirMercadoria" class="btn btn-primary" type="button"><i class="icon-white icon-plus"></i>&nbsp;Adicionar ao pedido</button>
                                    </div>
                                    <div class="col-md-12">&nbsp;</div>
                                    <div class="col-md-12">
                                        <table class="table table-striped table-bordered" id="tabelaMercadorias" name="tabelaMercadorias">
                                            <thead>
                                            <tr>
                                                <th>
                                                    <button type="button" id="chkTodos" class="btn btn-info" ><i class="icon-white"></i></button>
                                                </th>
                                                <th>
                                                    <span><?php echo "PRODUTO / SERVIÇO" ?></span>
                                                </th>
                                                <th>
                                                    <span>Quantidade</span>
                                                </th>
                                                <th>
                                                    <span>Valor Unitario</span>
                                                </th>
                                                <th>
                                                    <span>Total</span>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php if( @$pedidoMerc ) :?>
                                                <?php  foreach( $pedidoMerc as $merc ): ?>
                                                    <tr>
                                                        <td>
                                                            <button type="button" name="chkMercadoria[]" id="chkMercadoria<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo $merc['CD_MERCADORIA'] ?>" class="btn btn-info" onclick="verificaStatus($(this))"><i class=\"icon-white\"></i></button>
                                                            <input type="hidden" name="cdMercadoria[]" value="<?php echo $merc['CD_MERCADORIA'] ?>" />
                                                        </td>
                                                        <td>
                                                            <?php echo $merc['DS_MERCADORIA'] ?> <input type="hidden" name="ds_mercadoria-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo $merc['DS_MERCADORIA'] ?>" />
                                                        </td>
                                                        <td>
                                                            <?php echo $merc['QTD'] ?> <input type="hidden" name="qtdVendida-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo $merc['QTD'] ?>" />
                                                        </td>
                                                        <td>
                                                            <?php echo $merc['VL_TOTAL_BRUTO'] ?> <input type="hidden" name="vl_preco_unitario-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo number_format($merc['VL_TOTAL_BRUTO'],2, '.', '') ?>" />
                                                        </td>
                                                        <td>
                                                            <?php echo $merc['VL_TOTAL'] ?> <input type="hidden" name="vl_tot-<?php echo $merc['CD_MERCADORIA'] ?>" value="<?php echo number_format($merc['VL_TOTAL'],2, '.', '') ?>" />
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button id="btnExcluirMercadoria" class="btn  btn-info span3 pull-left" type="button"><i class="icon-white icon-trash"></i>&nbsp;Excluir selecionados</button>
                                    <input type="text" class="btn  btn-info span3 pull-right" readonly value="<?php echo ( @$totalPedido ? number_format($totalPedido, 2, ',', '.') : 0.00 )?>" id="totalPedido">
                                </div>

                            </fieldset>
                            <!-------------------------------------------------------------------------------------->
<!--                        </div>-->

<!--                        <div role="tabpanel" class="tab-pane" id="dadosPedido">-->
<!---->
<!--                        </div>-->

                    </div>
                    <div class="col-lg-12">
                        <hr>
<!--                        <button id="btnSalvarPedido" name="save" class="btn btn-primary btn" type="submit"><i class="icon-check icon-white"></i>&nbsp;Salvar</button>-->
                        <button id="btnSalvarPedido" name="save" class="btn btn-primary btn" type="button"><i class="icon-check icon-white"></i>&nbsp;Salvar </button>
                        <button id="btnCancelarPedido" class="btn btn-info btn" type="button"><i class="icon-remove icon-white"></i>&nbsp;Limpar</button>
                        <button id="btnVoltarListagemPedido"   class="btn btn-default btn" type="button"> <i class="i i-back"></i> Cancelar</button>

                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

<!-- Modal Pesquisa Cliente -->
<div id="pesquisaClienteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisaClienteModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <i class="icon-search icon-white"></i>
                <span class="text-info-modal">PESQUISA CLIENTE</span>
            </div>
            <div id="bodyPesquisaCliente" class="modal-body-xlarge"></div>
        </div>
    </div>
</div>
<!-- Modal Pesquisa Mercadoria -->
<div id="pesquisaMercadoriaModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisaMercadoriaModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <i class="icon-search icon-white"></i>
                <span class="text-info-modal">PESQUISA MERCADORIA - PREÇO DE VENDA</span>
            </div>
            <div id="bodyMercadoria" class="modal-body-xlarge"></div>
        </div>
    </div>
</div>
<!-- Modal Cadastra Cliente --><div id="cadastraClienteCompletoModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cadastraClienteCompletoModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">X</button>
                <i class="icon-search icon-white"></i>
                <span class="text-info-modal">Cadastrar Cliente</span>
            </div>
            <div id="bodyCadastroCliente" class="modal-body-xlarge"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        Pedido.init();
    });
</script>

