<section class="panel panel-default">

    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <i class="icon-check"></i>
                    <h3><?php echo utf8_encode("Relat&oacute;rio de notas fiscais ") ?></h3>
                </div> <!-- /widget-header -->
                <div class="widget-content">
                    <form id="formRelatorio" target="self" class="form-vertical validation-form"  action="/relatorio-nota/relatorio">
                        <input type="hidden" id="pdf" name="pdf" value="false" />
                        <div class="controls">

                            <div class="col-md-3">
                                <label for="" class="control-label text-info"><?php echo utf8_encode("De") ?></label>
                                <input class="form-control" type="date" id="dt_inicio" name="dt_inicio">
                                <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                            </div>

                            <div class="col-md-3">
                                <label for="" class="control-label text-info"><?php echo utf8_encode("At&eacute;") ?></label>
								<input class="form-control" type="date" id="dt_fim" name="dt_fim">
                                <span class="add-on btn-info"><i class="icon-calendar icon-white"></i></span>
                            </div>

                            <div class="col-md-2">
                                <label for="" class="control-label text-info">Nº Nota</label>
                                <input type="number" name="infNfe" id="infNfe" class="form-control"  placeholder="">
                            </div>

                            <div class="col-md-6">
                                <label for="" class="control-label text-info">Status</label><br/>
                                <label class="checkbox-inline"><input name="status" type="radio" value="E">Emitidas</label>
                                <label class="checkbox-inline"><input name="status" type="radio" value="N">Não Emitidas</label>
                                <label class="checkbox-inline"><input name="status" type="radio" value="C">Cancelados</label>
								<label class="checkbox-inline"><input name="status" type="radio" value="C">Todas</label>
                            </div>

                            <div class="col-md-12">
                                <hr>
                                <button id="btnPesquisarRelatorio" class="btn btn-primary btn" type="submit"><i class="icon-search icon-white"></i>&nbsp;Pesquisar</button>
                                <button id="btnCancelarRelatorio" class="btn btn-default btn" type="reset"><i class="icon-remove icon-white"></i>&nbsp;Limpar</button>
                                <button id="btnVoltarRelatorio"    class="btn btn-info btn"><i class="icon-arrow-left icon-white"></i>&nbsp;Voltar</button>
                            </div>

                        </div>

                    </form>
                </div> <!-- /widget-content -->
            </div> <!-- /widget -->
        </div> <!-- /span12 -->

    </div>
    <div id="modalDadosRelatorio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalDadosRelatorio" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="pull-right btn btn-danger"  id="btnFechar">Fechar</button>
                    <button type="button" class="pull-right btn-primary btn"  id="btnGerarPDF">Gerar PDF</button>
                    <span class="text-info-modal"><i class="icon-white icon-check"></i><?php echo utf8_encode("Relat&oacute;rio de Notas Fiscais") ?></span>
                </div>
                <div id="modalBodyDadosRelatorio" class="container-fluid" style="overflow-y:scroll"></div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {
        $('#formRelatorio').submit(function()
        {
            if ($("#pdf").val() == "false")
            {
                $("#modalBodyDadosRelatorio").load('/relatorio-nota/relatorio', {
                    dt_inicio: $("#dt_inicio").val(),
                    dt_fim: $("#dt_fim").val(),
                    infNfe: $("#infNfe").val(),
					status: $("input[name=status]:checked").val()
                });
                $("#modalDadosRelatorio").modal('show');
                return false;
            }
            else
            {
                return true;
            }

        });

        $('#btnGerarPDF').click(function() {
            $("#pdf").val("true");
            $("#formRelatorio").submit();
        });


        $('#btnFechar').click(function() {
            $("#pdf").val("false");
            $("#modalDadosRelatorio").modal('hide');
        });

        $('#btnVoltarRelatorio').click(function() {
            window.location = '/relatorio/index';
        });
    });
</script>