<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de clientes</h3>
                </div>
                <form class="form-horizontal" id="validation-form" action="/cliente/index" novalidate="novalidate" method="post" role="form">

                    <div class="controls">
                        <div class="col-md-6">
                            <label class="control-label text-info" for="name"><?php echo utf8_encode("Nome do Cliente") ?></label>
                            <?php echo $this->formElement($form->get("ds_nome_razao_social")) ?>
                            <?php echo $this->formElementErrors($form->get("ds_nome_razao_social")) ?>
                        </div>
                    </div>

                    <div class="controls">
                        <div class="col-md-3">
                            <label class="control-label text-info" for="nr_cgc_cpf"><?php echo utf8_encode("CPF / CNPJ") ?></label>
                            <?php echo $this->formElement($form->get("nr_cgc_cpf")) ?>
                            <?php echo $this->formElementErrors($form->get("nr_cgc_cpf")) ?>
                        </div>
                    </div>

                    <div class="controls">
                        <div class="col-md-3">
                            <label class="control-label text-info" for="ds_fone1">Telefone</label>
                            <?php echo $this->formElement($form->get("ds_fone1")) ?>
                            <?php //echo $this->formElementErrors($form->get("ds_fone1")) ?>
                        </div>
                    </div>

                    <div class="controls">
                        <div class="col-md-12">
                            <label class="control-label text-info" for="ds_endereco">Descrição do Endereço</label>
                            <?php echo $this->formElement($form->get("ds_endereco")) ?>
                            <?php echo $this->formElementErrors($form->get("ds_endereco")) ?>
                        </div>
                    </div>

                    <div class="controls">
                        <div class="col-sm-12">
                            <hr>
                            <?php echo $this->formElement($form->get("submit")) ?>
                            <?php echo $this->formElement($form->get("buttonLimpar")) ?>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="controls">
                    <div class="col-sm-12">
                        <button id="btnNovoCliente" class="btn btn-success" style="float:right; margin-top:5px; margin-right:5px;">
                            <i class="icon-plus icon-white"></i>
                             Adicionar novo cliente
                        </button>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                            <tr >
                                <!-- th nowrap>#</th -->
                                <th nowrap>Cliente</th>
                                <th nowrap>Sexo</th>
                                <th nowrap>CPF</th>
                                <th nowrap>Endere&ccedil;o</th>
                                <th nowrap>Telefone(s)</th>
                                <th nowrap>Email</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($clientes)) : ?>
                                <?php foreach ($clientes as $cliente): ?>
                                    <tr>
                                        <!-- td align="right"><?php //echo $cliente->CD_CLIENTE  ?></td -->
                                        <td align="left"><?php echo utf8_decode($cliente->DS_NOME_RAZAO_SOCIAL) ?></td>
                                        <td align="left"><?php echo $cliente->DS_SEXO ?></td>
                                        <td align="right"><?php echo ( strlen( $cliente->NR_CGC_CPF ) > 11 ? $util->mask($cliente->NR_CGC_CPF,'##.###.###/####-##') : $util->mask($cliente->NR_CGC_CPF,'###.###.###-##') ); ?></td>
                                        <td align="center"><?php echo utf8_decode($cliente->DS_ENDERECO) ?></td>
                                        <td align="center"><?php echo $cliente->DS_FONE1 . " / " . $cliente->DS_FONE2 ?></td>
                                        <td align="left"><?php echo utf8_decode($cliente->DS_EMAIL) ?></td>
                                        <td  align="center">
                                          <a href="/cliente/cadastro?id=<?php echo $cliente->CD_CLIENTE ?>" data-toggle="tooltip" data-placement="top" title="Editar Cliente" ><i class="fa fa-pencil"></i></a>   |
                                            <a href="/cliente/remover?id=<?php echo $cliente->CD_CLIENTE ?>"data-toggle="tooltip" data-placement="top" title="Excluir Cliente" ><i class="fa fa-trash-o"></i></a>
                                        </td>
                                        </th>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <!-- th nowrap>#</th -->
                                <th nowrap>Cliente</th>
                                <th nowrap>Sexo</th>
                                <th nowrap>CPF</th>
                                <th nowrap>Endere&ccedil;o</th>
                                <th nowrap>Telefone(s)</th>
                                <th nowrap>Email</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </tfoot>
                    </table>
                    <?php echo $this->paginationControl($clientes, 'Sliding', 'partials/paginator/control.phtml') ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {
        $("#btnNovoCliente").click(function() {
            window.location = "/cliente/cadastro";
        });
    });
</script>