<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header fluid">
                    <i class="icon-check"></i>
                    <h3>Relat&oacute;rios</h3>
                </div>
                <div class="widget-content">
                    <!--
                            <a  class="btn btn-info btn-block" href="/relatorio/atendimento">Relat&oacute;rio de Tipo de Atendimento</a><br />
                            <a  class="btn btn-info btn-block" href="/relatorio/caixa">Relat&oacute;rio de Caixa</a><br />
                            <a  class="btn btn-info btn-block" href="/relatorio/resumo-caixa">Relat&oacute;rio do Resumo de Caixa</a><br />
                    -->
                    <div class="widget-content">

                        <!-- LEFT -->
                        <div class="col-lg-4">
                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Atendimento
                                </header>
                                <div class="list-group bg-white">
                                    <a href="/relatorio-atendimento/pesquisa" class="list-group-item">
                                        Produtos / Serviços Vendidos
                                    </a>
                                </div>
                            </section>

                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Caixa
                                </header>
                                <div class="list-group bg-white">
                                    <a href="/relatorio-caixa-resumido/pesquisa" class="list-group-item">
                                        Caixa Resumido
                                    </a>
                                </div>
                            </section>
                        </div>

                        <!-- CENTER -->
                        <div class="col-lg-4">
                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Gerencial
                                </header>
                                <div class="list-group bg-white">
                                    <a href="/relatorio-vendas-mensal-tipo-pagamento/pesquisa" class="list-group-item">
                                        Vendas Mensais Por Tipo de Pagamento
                                    </a>
                                </div>
                            </section>
                        </div>
                        <div class="col-lg-4">
                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Agendamento
                                </header>
                                <div class="list-group bg-white">
                                    <a href="/relatorio-agendamentos/pesquisa" class="list-group-item">
                                        Relatório de Agendamentos
                                    </a>
                                </div>
                            </section>
                        </div>

                        <!-- RIGHT -->
                        <div class="col-lg-4">
                            <section class="panel panel-info portlet-item">
                                <header class="panel-heading">
                                    Estoque
                                </header>
                                <div class="list-group bg-white">
                                    <a href="/relatorio-inventario-estoque/pesquisa" class="list-group-item">
                                        Invent&aacute;rio de Estoque
                                    </a>
                                </div>
                            </section>
                        </div>


                        <div class="clear"></div>
                        <br>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>