<!DOCTYPE html>
<html lang="en" class="app">
    <head>
        <meta charset="utf-8" />
        <?php
        $session = new Zend\Session\Container("orangeSessionContainer");
        echo $this->headTitle('BSB Cloud')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0');

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//                ->prependStylesheet($this->basePath() . '/js/template/calendar/bootstrap_calendar.css')
                ->prependStylesheet($this->basePath() . '/css/template/app.css')
                ->prependStylesheet($this->basePath() . '/css/template/font.css')
                ->prependStylesheet($this->basePath() . '/css/template/icon.css')
                ->prependStylesheet($this->basePath() . '/css/template/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/template/animate.css')
                ->prependStylesheet($this->basePath() . '/css/template/bootstrap.css');

        echo $this->headScript()->prependFile($this->basePath() . '/js/ie/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/ie/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/ie/excanvas.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/ie/excanvas.js');
        ?>

        <!-- JQuery -->
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.10.4.custom.js"></script>
        <script type="text/javascript" src="/js/jquery.ui.core.js"></script>
        <script type="text/javascript" src="/js/jquery.ui.widget.js"></script>
        <!-- script type="text/javascript" src="/js/jquery.ui.position.js"></script -->
        <script type="text/javascript" src="/js/jquery.flexbox.js"></script>
        <script type="text/javascript" src="/js/jquery.dataTables.js"></script>
        <script type="text/javascript" src="/js/relogio.js"></script>
        <script type="text/javascript" src="/js/funcoesData.js"></script>
        <script type="text/javascript" src="/js/jquery.cpf-validate.1.0.min.js"></script>
        <script type="text/javascript" src="/js/jquery.maskMoney.js"></script>
        <script type="text/javascript" src="/js/funcoes.js"></script>

        <!-- Bootstrap -->
        <script type="text/javascript" src="/js/template/bootstrap.js"></script>
        <script type="text/javascript" src="/js/jquery.dataTables.bootstrap.js"></script>
        <script type="text/javascript" src="/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="/js/locales/bootstrap-datepicker.pt-BR.js"></script>
        <script type="text/javascript" src="/js/bootstrap-inputmask.js"></script>

        <!-- App -->
        <script type="text/javascript" src="/js/template/app.js"></script>
        <script type="text/javascript" src="/js/template/slimscroll/jquery.slimscroll.min.js"></script>

        <script type="text/javascript" src="/js/template/sortable/jquery.sortable.js"></script>
        <script type="text/javascript" src="/js/template/app.plugin.js"></script>

        <script type="text/javascript" src="/js/template/datatables/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="/js/template/datatables/jquery.csv-0.71.min.js"></script>

        <script type="text/javascript" src="/js/jquery.MultiFile.js"></script>

        <script src="/js/tinymce/tinymce.min.js" type="text/javascript"></script>
        <link rel="stylesheet" href="/js/template/datatables/datatables.css" type="text/css"/>
		
		<!--JS util-->
		<script type="text/javascript" src="/js/orangeweb/util.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				Util.init();
			});
		</script>

        <script type="text/javascript" >
            var _horaInicio;
            var _horaFim;
            var _intervalo;
        </script>
		
		<!-- cdn for modernizr, if you haven't included it already -->
		<script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
		<!-- polyfiller file to detect and load polyfills -->
		<script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
		<script>
		  webshims.setOptions('waitReady', false);
		  webshims.setOptions('forms-ext', {types: 'date'});
		  webshims.polyfill('forms forms-ext');
		</script>
    </head>
    <body onload="verificaAgenda(_horaInicio, _horaFim, _intervalo);">
        <?php $url = explode('?', $_SERVER['REQUEST_URI']); ?>
        <section class="vbox">
            <header class="bg-primary header header-md navbar navbar-fixed-top-xs box-shadow">
                <div class="navbar-header aside-md dk">
                    <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
                        <i class="fa fa-bars"></i>
                    </a>
                    <a href="<?php echo $this->url('home') ?>" class="navbar-brand" style="margin-left: 34px;">
                        <img src="/img/logo-orange-small.png" class="m-r-sm">
                    </a>
                </div>
                <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user user">
                    <li class="hidden-xs">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"  title="Idiomas">
                            <i class="i i-earth"></i>
                        </a>
                        <section class="dropdown-menu aside-xl animated flipInY">
                            <section class="panel bg-white">
                                <header class="panel-heading b-light bg-light">
                                    <strong>IDIOMAS</strong>
                                </header>
                                <div class="list-group list-group-alt">
                                    <a href="#" class="media list-group-item">
                                        <span class="pull-left thumb-sm">
                                            <img src="/img/iconeBrasil.gif" class="img-circle">
                                        </span>
                                        <span class="media-body block m-b-none">
                                            Brasil<br>
                                        </span>
                                    </a>
                                    <div class="list-group list-group-alt">
                                        <!--<a href="#" class="media list-group-item">
                                            <span class="pull-left thumb-sm">
                                                <img src="/img/iconeEua.gif" alt="Brasil" class="img-circle">
                                            </span>
                                            <span class="media-body block m-b-none">
                                                USA<br>
                                            </span>
                                        </a>
                                        <div class="list-group list-group-alt">
                                            <a href="#" class="media list-group-item">
                                                <span class="pull-left thumb-sm">
                                                    <img src="/img/espanha.gif" alt="Brasil" class="img-circle">
                                                </span>
                                                <span class="media-body block m-b-none">
                                                    España<br>
                                                </span>
                                            </a>
                                        </div>-->
                                    </div>
                                </div>
                            </section>
                        </section>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="thumb-sm avatar pull-left">
                                <img src="/img/a0.png">
                            </span>
                            <?php echo utf8_encode($session->dsLoja); ?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight">
                            <span class="arrow top"></span>
                            <li>
                                <a href="/perfil">Perfil</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="/index/logout">Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </header>
            <section>
                <section class="hbox stretch">
                    <!-- .aside -->
                    <aside class="bg-black aside-md hidden-print" id="nav">
                        <section class="vbox">
                            <section class="w-f scrollable">
                                <div class=slim-scroll data-height=auto data-disable-fade-out=true data-distance=0 data-size=10px data-railOpacity=0.2>
                                    <!-- nav -->
                                    <nav class="nav-primary hidden-xs">
                                        <?php
                                            require('menu.phtml');
                                        ?>
                                    </nav>
                                    <!-- / nav -->
                                </div>
                            </section>
                            <footer class="footer hidden-xs no-padder text-center-nav-xs">
                                <a href="#nav" data-toggle="class:nav-xs" class="btn btn-icon icon-muted btn-inactive m-l-xs m-r-xs">
                                    <i class="i i-circleleft text"></i>
                                    <i class="i i-circleright text-active"></i>
                                </a>
                            </footer>
                        </section>
                    </aside>
                    <!-- /.aside -->
                    <section id="content">
                        <section class="hbox stretch">
                            <section>
                                <section class="vbox">
                                    <section class="scrollable padder">
                                        <?php echo $this->content; ?>
                                    </section>
                                </section>
                            </section>
                        </section>
                    </section>
                </section>
            </section>
        </section>
    </body>
</html>