<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<div class="main">
    <div class="row-fluid">
        <div class="widget stacked">
            <div class="widget-header">
                <i class="icon-check"></i>
                <h3><?php echo utf8_encode("Cadastro de maca / profissional") ?></h3>
            </div> <!-- /widget-header -->
            <div class="widget-content">
                <form class="form-vertical" id="validation-form" action="/maca/cadastrar" method="post">
                    <table style="width: 100%;">
                        <tr>
                            <td>
                                <?php echo $this->formElement($form->get("cd_loja")) ?>
                                <?php echo $this->formElementErrors($form->get("cd_loja")) ?>
                                <div class="controls">
                                    <div  class="col-md-12">
                                        <label class="control-label text-info" for="name"><?php echo utf8_encode("Identifica&ccedil;ao") ?></label>
                                        <?php echo $this->formElement($form->get("ds_identificacao")) ?>
                                        <?php //echo $this->formElementErrors($form->get("ds_identificacao")) ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label for="validateSelectProfissional" class="control-label text-info"><?php echo utf8_encode("Profissional") ?></label>
                                        <?php echo $this->formElement($form->get("cd_funcionario")) ?>
                                        <?php //echo $this->formElementErrors($form->get("cd_funcionario")) ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <hr>
                                        <?php echo $this->formElement($form->get("submit")) ?>
                                        <?php echo $this->formElement($form->get("return")) ?>
                                        <?php echo $this->formElement($form->get("reset")) ?>
                                    </div>
                            </td>
                        </tr>
                    </table>
                </form>
            </div> <!-- /widget-content -->
        </div> <!-- /widget -->
        <!--</div>  /span12 -->
    </div>
</div>