<div class="hero-unit">
	<center>
            <br /><br /><br /><br />
			<img src="<?php echo $this->basePath('img/logo-orange.png'); ?>" style="width:45%;" border="0" />
			<br/><b>Loja:</b> <?php echo $cdLoja?> - <?php echo utf8_encode($nomeLoja)?>
            <br/>
            <br/>© 2019 Todos os direitos reservados.
            <br/><a href="http://www.bsbgestao.com.br" target="_blank">www.bsbgestao.com.br</a>
    </center>
</div>