<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <?php if (count($this->flashMessenger()->getMessages())) : ?>
                    <?php
                    foreach ($this->flashMessenger()->getMessages() as $value):
                        $key = key($value);
                        $message = current($value);
                        ?>
                        <div class="alert alert-<?php echo $key ?>">
                            <button type="button" class="close" data-dismiss="alert" >&times;</button>
                            <?php echo $message ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>

                <div class="widget-header">
                    <h3>
                        Caixa 0<?php echo $nrCaixa; ?> - <?php echo $dtCaixa; ?>
                    </h3>
                </div>

                <form id="frmCaixaC" method="post">
                    <input type="hidden" name="rdCaixa" value="<?php echo $nrCaixa; ?>">
                </form>
                <div class="widget-content">

                   <!-- <ul id="tabsCaixas" class="nav nav-tabs">
                        <li id="aba1"><a href="#entradaPedidos" data-toggle="tab" class="active cliCad">Entrada de pedidos</a></li>
                       <li id="aba2"><a href="#transporteFrete" data-toggle="tab" class="cliCad">Transporte / Frente e outras despesas assessórias</a></li>
                    </ul>-->

<!--                    <div class="tab-content">-->
                    <div class="span6 pull-right">
                        <a href="/caixa/index" title="Retornar a tela de seleção de caixa">
                            <button type="button" class="btn btn-info" onclick="">Seleção de Caixa</button>
                        </a>
                    </div>

                        <div class="span10" style="padding-top: 5px;padding-bottom: 7px;">
                            <label class="control-label text-info" for="name">
                                <?php echo utf8_encode("Tipos de pedido:") ?>
                            </label>

                            <select>
                                <option value="1">Pedido Venda</option>
                            </select>
                        </div>
                        <div class="tab-pane span12" id="entradaPedidos">
                            <ul id="tabsSubCaixas" class="nav nav-tabs">
                                <li id="aba1"><a href="#pedidos" data-toggle="tab" class="active cliCad">Pedidos de Venda</a></li>
<!--                                <li id="aba2"><a href="#ordemServico" data-toggle="tab" class="cliCad">Ordens de serviço</a></li>-->
<!--                                <li id="aba3"><a href="#rebemimentoPedidos" class="cliRap" data-toggle="tab">Recebimento pedido posterior / Contas a receber</a></li>-->
                            </ul>

                            <div class="tab-content">
                                <div class="tab-pane span12" id="pedidos">
                                    <div class="span12"></div>
                                    <div class="span10" style="overflow-x: scroll;height:300px;">
                                        <label class="control-label text-primary" for="name">Relação de pedido(s) em aberto</label>
                                        <table class="table table-striped  table-hover" style="width: 100%;">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>Nª pedido</th>
                                                    <th>Nome do cliente</th>
                                                    <th>Valor bruto</th>
                                                    <th>Desconto</th>
                                                    <th>Valor líquido</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                if (isset($listaPedidos)) {
                                                    foreach ($listaPedidos as $value) {
                                                        $desconto = (float)($value['VL_TOTAL_BRUTO'] - $value['VL_TOTAL_LIQUIDO']);
                                                        echo '<tr>
                                                                <td><input type="checkbox" name="ckPedido[]" value="\''. $value['NR_PEDIDO'] .'\'" onclick="somaTotal(this.checked,\'' . (number_format($value['VL_TOTAL_BRUTO'], 2, ',', '.')) . '\',\'' . (number_format($desconto, 2, ',', '.')) . '\');"></td>
                                                                <td>' . $value['NR_PEDIDO'] . '</td>
                                                                <td>' . utf8_encode($value['DS_NOME_RAZAO_SOCIAL']) . '</td>
                                                                <td>' . (number_format($value['VL_TOTAL_BRUTO'], 2, ',', '.')) . '</td>
                                                                <td>' . (number_format($desconto, 2, ',', '.')) . '</td>
                                                                <td>' . (number_format($value['VL_TOTAL_LIQUIDO'], 2, ',', '.')) . '</td>
                                                            </tr>';
                                                    }
                                                }
                                                else
                                                {
                                                    echo '<tr>
                                                            <td colspan="3">Nenhum registro</td>
                                                        </tr>';
                                                }
                                                ?>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>

                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!--<div class="tab-pane" id="ordemServico">
                                    <div class="span10" style="overflow-x: scroll;height:340px;">
                                        <label class="control-label text-primary" for="name">Relação de ordens de serviço em aberto</label>
                                        <table class="table" style="width: 100%;">
                                            <thead>
                                                <tr>
                                                    <th>Nome do cliente</th>
                                                    <th>Representante</th>
                                                    <th>Vl bruto</th>
                                                    <th>Vl desconto</th>
                                                    <th>Vl frete</th>
                                                    <th>Vl líquido</th>
                                                    <th>Frete</th>
                                                    <th>CNPJ/CPF</th>
                                                    <th>Cliente</th>
                                                    <th>Fone do cliente</th>
                                                    <th>Bco</th>
                                                    <th>Agência</th>
                                                    <th>C/C</th>
                                                    <th>Cód. cliente</th>
                                                    <th>UF</th>
                                                    <th>NF</th>
                                                    <th>Marcado</th>
                                                    <th>Nº OS</th>
                                                    <th>Nº cupom</th>
                                                    <th>Subs. tributária</th>
                                                    <th>Prazo</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>-->
                                <!--<div class="tab-pane" id="rebemimentoPedidos">
                                    <div class="col-md-12" style="padding-top: 5px;padding-bottom: 7px;">
                                        <input type="checkbox" >Pesquisar cliente
                                        <select>
                                            <option>Selecione...</option>
                                        </select>

                                        <button id="btnPesquisa" type="button" class="btn btn-primary">
                                            <i class="fa fa-search"></i>
                                        </button>

                                        Data inicial: <input type="text" id="dt_data">
                                        Data final: <input type="text" id="dt_data">

                                        <button id="btnPesquisa" type="button" class="btn btn-primary">
                                            <i class="fa fa-search"></i>
                                        </button>

                                        <input type="button" class="btn btn-success" id="btnPesquisa" value="Pré fatura">
                                    </div>
                                    <div class="col-md-12" style="overflow-x: scroll;height:250px;">
                                        <label class="control-label text-primary" for="name">Relação de pedido(s) posteriores NÃO recebidos</label>
                                        <table class="table" style="width: 100%;">
                                            <thead>
                                                <tr>
                                                    <th>Nª pedido</th>
                                                    <th>Nome do cliente</th>
                                                    <th>Representante</th>
                                                    <th>Vl bruto</th>
                                                    <th>Desconto</th>
                                                    <th>Vl frete</th>
                                                    <th>Vl líquido</th>
                                                    <th>Frete</th>
                                                    <th>CNPJ/CPF</th>
                                                    <th>Cliente</th>
                                                    <th>Fone do cliente</th>
                                                    <th>Bco</th>
                                                    <th>Agência</th>
                                                    <th>C/C</th>
                                                    <th>UF</th>
                                                    <th>NF</th>
                                                    <th>Tipo pedido</th>
                                                    <th>Situação</th>
                                                    <th>Nº cupom</th>
                                                    <th>Subs. tributária</th>
                                                    <th>Prazo</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div-->
                            </div>

                            <div class="col-md-12">&nbsp;</div>
                            <div class="col-md-12" style="padding-left: 0px;">
                                <div class="col-md-6" style="padding-left: 0px;padding-right: 0px;">
                                   <!-- <label class="control-label text-info" for="name">&nbsp;</label>
                                    <input type="button" class="btn btn-info" id="btnAciona" value="Acionar gaveta">
                                    -->

                                    <label class="control-label text-info" for="name">&nbsp;</label>
                                    <input type="button" class="btn btn-info" id="btnAtualizaCaixa" value="Atualizar caixa">

                                    <label class="control-label text-info" for="name">&nbsp;</label>
                                    <input type="button" class="btn btn-info" id="btnVer" value="Ver pedido">

                                    <label class="control-label text-info" for="name">&nbsp;</label>
                                    <input type="button" class="btn btn-info" id="btnRecebe" value="Receber pedido">
                                </div>
                                <div class="col-md-6" style="padding-left: 0px;">
                                    <div class="col-md-4" style="padding-left: 0px;">
                                        <label class="control-label text-info" for="name"><?php echo utf8_encode("Total") ?></label>
                                        <input type="text" id="txtVlTotal" class="moeda form-control" value="0,00" readonly="readonly">
                                    </div>
                                    <div class="col-md-4" style="padding-left: 0px;">
                                        <label class="control-label text-info" for="name"><?php echo utf8_encode("Valor desconto") ?></label>
                                        <input type="text" id="txtVlDesconto" class="moeda form-control" value="0,00" readonly="readonly">
                                    </div>
                                    <!--<div class="col-md-3" style="padding-left: 0px;">
                                        <label class="control-label text-info" for="name"><?php /*echo utf8_encode("Frete/Outros") */?></label>
                                        <input type="text" id="txtFreteOutros" class="moeda form-control" value="0,00" readonly="readonly">
                                    </div>-->
                                    <div class="col-md-4" style="padding-left: 0px;">
                                        <label class="control-label text-info" for="name"><?php echo utf8_encode("Total geral") ?></label>
                                        <input type="text" id="txtTotalGeral" class="moeda form-control" value="0,00" readonly="readonly">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">&nbsp;</div>

                           <!-- <div class="col-md-12">
                                <label class="control-label text-info" for="name">Total geral</label>
                                <input type="text" id="txtTotalGeral1" class="text-primary" value="0,00">

                                <label class="control-label text-info" for="name">Pago</label>
                                <input type="text" id="txtTotalGeral2" class="text-primary" value="0,00">
                            </div>-->
                        </div>
                       <!-- <div class="tab-pane span12" id="transporteFrete">
                            <fieldset>
                                <legend>Dados do transporte / Frete</legend>

                                <div class="span2" style="padding-bottom:5px;">
                                    <label class="control-label text-info" for="name">
                                        <?php /*echo utf8_encode("Transporte") */?>
                                    </label>

                                    <select>
                                        <option value="">Selecione...</option>
                                    </select>
                                </div>
                                <div class="span2" style="float:left;clear:right;padding-left:10px;">
                                    <label class="control-label text-info" for="name">
                                        <?php /*echo utf8_encode("Valor do frete") */?>
                                    </label>
                                    <br>
                                    <input type="text" id="txtVlTotal">
                                </div>
                                <div class="span2" style="float:left;clear:right;padding-left:10px;">
                                    <label class="control-label text-info" for="name">
                                        <?php /*echo utf8_encode("Data da entrega") */?>
                                    </label>
                                    <br>
                                    <input type="text" id="txtVlDesconto1">
                                </div>
                                <div class="span2" style="float:left;clear:right;padding-left:10px;">
                                    <label class="control-label text-info" for="name">
                                        <?php /*echo utf8_encode("Frete por conta do:") */?>
                                    </label>
                                    <br>
                                    <input type="radio" id="txtFreteOutros" name="rdFrete">1-Emitente
                                    <input type="radio" id="txtFreteOutros" name="rdFrete">2-Destinatário
                                </div>
                                <div class="span2" style="float:left;clear:right;padding-left:10px;">
                                    <label class="control-label text-info" for="name">
                                        <?php /*echo utf8_encode("Qtd caixas/volume") */?>
                                    </label>
                                    <br>
                                    <input type="text" id="txtTotalGeral3">
                                </div>
                            </fieldset>
                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>
</section>

<div id="divModalPagamento" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divModalPagamento" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
            <h4 class="text-info-modal modalPagamento">RECEBIMENTO PEDIDO</h4>
        </div>
            <div class="modal-body" id="bodyDivModalPagamento"></div>
        </div>
    </div>
</div>

<div id="divModalPedido" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divModalPedido" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
            <h4 class="text-info-modal modalPedido">PEDIDO</h4>
        </div>
            <div class="modal-body" id="bodyDivModalPedido"></div>
        </div>
    </div>
</div>


<div id="divModalCpfNota" class="modal fade" tabindex="999999" role="dialog" aria-labelledby="divModalCpfNota" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h4 class="text-info-modal modalCpfNota">CPF na nota?</h4>
            </div>
            <div class="modal-body" id="bodyDivModalCpfNota"></div>
        </div>
    </div>
</div>

<div id="divModalAguarde" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divModalAguarde" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="text-info-modal modalAguarde  text-center">
                    <i class="fa fa-compass"></i>&nbsp;Processando ...
                </h4>
            </div>

        </div>
    </div>
</div>


<script>
    $(document).ready(function() {
                
        $(".moeda").maskMoney({showSymbol:false, symbol:"", decimal:",", thousands:"."});
        
        $('#tabsCaixas a[href="#entradaPedidos"]').tab('show');
        $('#tabsSubCaixas a[href="#pedidos"]').tab('show');
        
        $('#btnAtualizaCaixa').click(function(){
            //window.location = '/caixa/caixa';
            $('#frmCaixaC').submit();
        });
         
        $('#btnVer').click(function(){
            var nrPedido;
            var cont = 0;
            $("input[name='ckPedido[]']").each(function(){
                if(this.checked)
                {
                    cont++;
                    nrPedido = this.value.replace("\'","").replace("\'","");
                }
            });
            
            if (cont == 1) {
                $('#bodyDivModalPedido').load('/pedido/orcamento',{
                    nrPedido: nrPedido,
                    modal   : 'show'
                });
                $('#divModalPedido').modal('show');
            } else if(cont == 0) {
                alert('Selecione um pedido!');
            } else if (cont > 1) {
                alert('Selecione apenas um pedido!');
            }
        });
         
        somaTotal = function(operacao, vlTotal, vlDesconto)
        {
            var total;
            var desc;
            var totalGeral;

            if(operacao)
            {
                total = parseFloat($('#txtVlTotal').val().replace(",",  ".")) + parseFloat(vlTotal.replace(/\./g, "").replace(",",  "."));
                desc = parseFloat($('#txtVlDesconto').val().replace(",",  ".")) + parseFloat(vlDesconto.replace(/\./g, "").replace(",",  "."));
                totalGeral =  total - desc;
            }
            else
            {
                total = parseFloat($('#txtVlTotal').val().replace(",",  ".")) - parseFloat(vlTotal.replace(/\./g, "").replace(",",  "."));
                desc = parseFloat($('#txtVlDesconto').val().replace(",",  ".")) - parseFloat(vlDesconto.replace(/\./g, "").replace(",",  "."));
                totalGeral = total + desc;
            }

            $('#txtVlTotal').val(formatReal(total));
            $('#txtVlDesconto').val(formatReal(desc));
            $('#txtTotalGeral').val(formatReal(totalGeral));
            
        }
        
        $('#btnRecebe').click(function(){
            var arrPedido = new Array();
            $("input[name='ckPedido[]']").each(function(){
                if(this.checked)
                {
                    arrPedido.push(this.value.replace("\'","").replace("\'",""));
                }
            });
            
            if (arrPedido.length == 1) {
                //if (confirm('Deseja receber o pedido nº '+arrPedido+'?')) {
                    $('#bodyDivModalPagamento').load('/caixa/recebepedido?nrPedido=' + arrPedido + '&vlPedido=' + $('#txtTotalGeral').val() + '&nrCaixa=<?php echo $nrCaixa; ?>');
                    $('#divModalPagamento').modal('show');
                //}
            } else  if (arrPedido.length > 1) {
                alert('Selecione apenas um pedido!');
            } else {
                alert('Selecione um pedido!');
            }
        });
    });
</script>