<div class="tab-content">
    <form id="frmFechamentoCaixa" action="/caixa/fechamentocaixa" method="post">
        <table style="width: 100%;">
            <tr>
                <td>
                    <div class="fluid widget stacked" >
                        <div class="controls">
                            <div class="col-md-4">
                                <label class="control-label text-info" for="name">Caixa:</label>
                                <select style="width:100%;" required="required" name="nr_caixa" class="form-control">
                                    <option value="">Selecione...</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label class="control-label text-info" for="name">Data:</label>
                                <input type="text" name="dtCaixa" value="<?php echo date('d/m/Y') ?>" class="form-control" required="required">
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <br />
                    <div class="controls">
                        <div class="col-md-12">
                            <input type="submit" class="btn btn-danger btn-large" id="btnFechaCaixa" value="Fechar caixa">
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('#dtCaixa').datepicker(
                            {
                                format: 'dd/mm/yyyy',
                                language: 'pt-BR',
                                todayBtn: "linked"
                            }
                        );        
    });
</script>