<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <?php if (count($this->flashMessenger()->getMessages())) : ?>
                    <?php
                    foreach ($this->flashMessenger()->getMessages() as $value):
                        $key = key($value);
                        $message = current($value);
                        ?>
                        <div class="alert alert-<?php echo $key ?>">
                            <button type="button" class="close" data-dismiss="alert" >&times;</button>
                            <?php echo $message ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="widget-header ">
                    <i class="icon-check"></i>
                    <h3>Seleção de Caixa</h3>
                </div>
                <div class="widget-content">
                    <div class="span6 pull-right">
                        <input type="button" class="btn btn-info" id="btnAbertura" value="Abertura de caixa">
                        <input type="button" class="btn btn-info" id="btnFechamento" value="Fechamento de caixa">
                        <input type="button" class="btn btn-info" id="btnMovimentacao" value="Movimentação de caixa">
                    </div>

                    <div class="span12"></div>

                    <ul id="tabsCaixa" class="nav nav-tabs">
                        <li id="aba1"><a href="#caixaDisponivel" data-toggle="tab" class="active cliCad">Caixas disponíveis</a></li>
                    </ul>

                    <div class="tab-content span12">
                        <form id="frmCaixa" action="/caixa/caixa" method="post">
                            <div class="tab-pane" id="caixaDisponivel">

                                <div class="col-md-12"></div>

                                <table class="table table-striped  table-hover">
                                    <thead>
                                        <tr>
                                            <th>&nbsp;</th>
                                            <th style="width: 25%;">Número do caixa</th>
                                            <th style="width: 50%;">Operador (a)</th>
                                            <th style="width: 25%;">Data abertura</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if (isset($listaCaixas)) {
                                            foreach ($listaCaixas as $value) {
                                                //$disabled = (($value['CD_FUNCIONARIO'] == $cdFuncionario)) ? '' : ' disabled="disabled" ';
                                                $disabled = '';
                                                echo '<tr>
                                                            <td><input type="radio" class="radio" name="rdCaixa" '.$disabled.' value="' . $value['NR_CAIXA'] . '"/></td>
                                                            <td>' . $value['NR_CAIXA'] . '</td>
                                                            <td>' . $value['DS_FUNCIONARIO'] . '</td>
                                                            <td>' . date('d/m/Y', strtotime($value['DT_ENTRADA'])) . '</td>
                                                        </tr>';
                                            }
                                        } else {
                                            echo '<tr>
                                                    <td colspan="3">Nenhum registro</td>
                                                </tr>';
                                        }
                                        ?>
                                    </tbody>
                                </table>


                                <div class="col-md-12"></div>
                                <div class="col-md-12">
                                    <input type="submit" class="btn btn-success" id="btnUtilizar" value="Utilizar caixa" onclick="return validaSelCaixa();">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="divCaixaFuncionario" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divCaixaFuncionario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h4 class="text-info-modal modalClienteAgenda">ABERTURA DE CAIXA</h4>
            </div>
            <div class="modal-body" id="bodyDivCaixaFuncionario"></div>
        </div>
    </div>
</div>

<div id="divCaixaFechamento" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divCaixaFechamento" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h4 class="text-info-modal modalCaixaFechamento">FECHAMENTO DE CAIXA</h4>
            </div>
            <div class="modal-body" id="bodyDivCaixaFechamento"></div>
        </div>
    </div>
</div>

<div id="divCaixaMovimentacao" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divCaixaMovimentacao" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h4 class="text-info-modal modalCaixaMovimentacao">MOVIMENTAÇÃO DE CAIXA</h4>
            </div>
            <div class="modal-body-xlarge" id="bodyDivCaixaMovimentacao"></div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function() {
        $('#dt_data').datepicker({format: 'dd/mm/yyyy',
            language: 'pt-BR',
            todayBtn: "linked"});

        $('#tabsCaixa a[href="#caixaDisponivel"]').tab('show');

        $('.closeDivCaixaFuncionario').click(function() {
            $('#divCaixaFuncionario').modal('hide');
        });

        $('#btnAbertura').click(function() {
            $('#bodyDivCaixaFuncionario').load('/caixa/caixafuncionario');
            $('#divCaixaFuncionario').modal('show');
        });
        
        $('#btnFechamento').click(function() {
            $('#bodyDivCaixaFechamento').load('/caixa/fechamentocaixa');
            $('#divCaixaFechamento').modal('show');
        });
        
        $('#btnMovimentacao').click(function() {
            if(validaSelCaixa())
            {
                $('#bodyDivCaixaMovimentacao').html('');
                $('#bodyDivCaixaMovimentacao').load('/caixa/movimentacaocaixa?nrCaixa=1');
                $('#divCaixaMovimentacao').modal('show');
            }
        });
        
        validaSelCaixa = function()
        {            
            var c = 0;
            $('input[name=rdCaixa]').each(function(k,v){
                if(v.checked){ c++; }
            });
            
            if(c > 0)
            {
                return true;
            }
            else
            {
                alert('Selecione um caixa');
                return false;
            }
            
        }
    });
</script>