<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de Serviço/ Mercadoria </h3>
                </div>	
				<form class="form-horizontal" id="validation-form" action="/mercadoria/index" novalidate="novalidate" method="post" role="form">
					<div class="controls">
						<div class="col-md-12">
							<label>Descrição da mercadoria</label>
							<input type="text" class="form-control" name="ds_mercadoria" id="campo_pesquisa" />
                            <hr/>
						</div>

                        <div class="col-md-9">
                            <button type="submit" " id="btnSubmit" class="btn btn-primary btn" style="" value="">
                                <i class="fa fa-search"></i>
                                Pesquisar
                            </button>
                            <button type="button" name="buttonLimpar" class="btn btn-default btn" id="btnLimparFormulario" onclick="javascript:window.location.href='/cliente/index'" value="">
                                <i class="i i-back"></i>
                                Limpar
                            </button>
                        </div>
					</div>
                    <div class="controls">
                        <div class="col-md-12">
                            <label class="control-label text-info" for="name">&nbsp;</label>
                            <a href="/mercadoria/cadastrar">
                                <button id="btnNovoServicoMercadoria" type="button" class="btn btn-success" style="float:right;">
                                    <i class="i glyphicon-plus"></i>
                                    Adicionar Serviço/ Mercadoria
                                </button>
                            </a>
                        </div>

                    </div>
				</form>
            </div>
        </div>
		
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                            <tr >
                                <!-- th nowrap>#</th -->
                                <th nowrap>Cod.</th>
                                <th nowrap>Descrição</th>
                                <th nowrap>Unidade de Venda</th>
                                <th nowrap>Preço Venda</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($mercadorias)) : ?>
                                <?php foreach ($mercadorias as $mercadoria): ?>
                                    <tr>
                                        <td align="left"><?php echo $mercadoria->CD_MERCADORIA  ?></td>
                                        <td align="left"><?php echo utf8_encode($mercadoria->DS_MERCADORIA) ?></td>
                                        <td align="left"><?php echo $mercadoria->CD_UNIDADE_VENDA ?></td>
                                        <td align="right"><?php  echo ( $mercadoria->VL_PRECO_VENDA ? number_format(@$mercadoria->VL_PRECO_VENDA,2, '.', '') : '0.00' ) ?></td>
                                        <td  align="center">
                                          <a href="/mercadoria/editar?id=<?php echo $mercadoria->CD_MERCADORIA ?>" ><i class="fa fa-pencil"></i></a> |
                                            <a href="/mercadoria/remover?id=<?php echo $mercadoria->CD_MERCADORIA ?>" ><i class="fa fa-trash-o"></i></a>
                                        </td>
                                        </th>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>  
                        <tfoot>
                            <tr>
                                <!-- th nowrap>#</th -->
                                <th nowrap>Descrição</th>
                                <th nowrap>Unidade de Venda</th>
                                <th nowrap>Preço Venda</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </tfoot>
                    </table>
                    <?php echo $this->paginationControl($mercadorias, 'Sliding', 'partials/paginator/control.phtml') ?>
                </div>
            </div>
        </div>
    </div>
</section>