<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="controls">
                    <div class="col-md-3">
                        <label class="text-info">Pesquisar por</label>
                        <select class="form-control" name="st_tipo_pesquisa" id="st_tipo_pesquisa">
                            <option value="1">Código</option>
                            <option value="2" selected="selected">Descrição</option>
                            <option value="3">Referência</option>
                            <option value="4">Marca/Embalagem</option>
                            <option value="5">Modelo/Cor</option>
                            <option value="6">Parte/Descrição</option>
                            <option value="7">Código Fornecedor</option>
                            <option value="8">Fabricante</option>
                            <option value="9">Observação</option>
                        </select>
                    </div>
                </div>
                <div class="controls">
                    <div class="col-md-6">
                        <label class="text-info">Procurar por</label>
                        <input type="text" class="form-control" name="codigoMercadoria" id="codigoMercadoria" value="" />
                    </div>
                </div>
                <div class="controls">
                    <div class="col-md-2">
                        <label class="text-info">&nbsp;</label>
                        <div>
                            <button type="button" class="btn btn-info" id="btnPesquisaMercadoria">
                                <i class="i i-search"></i>
                                Localizar
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-md-12"></div>
                <!--style=" width: 98%; overflow-x: scroll;"-->
                <div class="controls">
                    <div class="table-responsive">
                        <br />
                        <table class="table table-hover">
                            <thead>
                            <td>Código</td>
                            <td>Descrição</td>
                            <td>Estoque</td>
                            <td>Reserva</td>
                            <td>Qtd diponível</td>
                            <td>Preço à vista</td>
                            <td>Preço venda</td>
                            <td>Preço promoção</td>
                            </thead>
                            <tbody id="tListaMercadoria"> </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="13">Total de Registro(s): </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="controls">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary concluir">
                            <i class="i i-ok"></i>
                            Ok
                        </button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default cancelar">
                            <i class="i i-cancel"></i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#btnPesquisaMercadoria').click(function() {
            if($('#codigoMercadoria').val() == '') return false;
            Util.recuperaMercadoriaPorParamentro();
        });

        $('.concluir').click(function() {
            if($('input[name="co_mercadoria"]:checked').val() == '')
            {
                return false;
            }

            $.ajax({
                url: "/mercadoria/recupera-mercadoria-por-codigo",
                type: "POST",
                dataType: "json",
                data: {
                    CD_MERCADORIA: $('input[name="co_mercadoria"]:checked').val()
                },
                success: function(data) {
                    if (data.result == 'erro') {
                        alert(data.message);
                        return false;
                    }

                    $('#CD_MERCADORIA').val($('input[name="co_mercadoria"]:checked').val());
                    $('#ds_mercadoria').val(decodeURIComponent(escape(data.data.DS_MERCADORIA)));
                    $('#vl_preco_unitario').val(formatReal(data.data.VL_PRECO_VENDA));
					$("#vl_preco_unitario").blur();
                    $('#tp_retirada').val('E');
                    $('#qt_mercadoria').val('1');

                    $('.modal').modal('hide');
                }
            });
        });
    });
</script>