<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">
				<h3 class="tit">Cadastrar usuário web</h3>
				<hr />   
				<form action="/perfil/cadastrar" method="post">
					<div class="col-xs-10 col-md-10">
						<label>Nome: </label>
						<input class="form-control" type="text" name="NM_USUARIO" maxlength="50" placeholder="Nome do usuario" required>
					</div>

                    <div class="col-xs-5 col-md-5">
                        <label>Login: </label>
                        <input class="form-control" type="text" name="NM_USUARIO" maxlength="50" placeholder="Login do usuário" required>
                    </div>

                    <div class="col-xs-5 col-md-5">
                        <label>Senha: </label>
                        <input class="form-control" type="password" name="NM_USUARIO" maxlength="50" placeholder="Senha do usuário" required>
                    </div>

                    <div class="col-xs-5 col-md-5" id="div_csosn">
                        <label>Loja: </label>
                        <select class="form-control" name="CSOSN"  >
                            <option value="">Selecione...</option>
                        </select>
                    </div>

                    <div class="col-xs-5 col-md-5">
                        <label>Email: </label>
                        <input class="form-control" type="text" name="NM_USUARIO" maxlength="50" placeholder="Email" required>
                    </div>

                    <div class="col-xs-5 col-md-5">
                        <label>Telefone: </label>
                        <input class="form-control" type="text" name="NM_USUARIO" maxlength="50" placeholder="(99) 9999-9999" required>
                    </div>

                    <div class="col-xs-5 col-md-5" id="div_csosn">
                        <label>Perfil do usuário: </label>
                        <select class="form-control" name="CSOSN"  >
                            <option value="">Selecione...</option>
                        </select>
                    </div>

                        <div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/usuario/index"><button type="button" class="btn btn-default">
                                    <i class="i i-back"></i>
									Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
			