<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de Usuários Web</h3>
                </div>
            </div>
            <form class="form-horizontal" id="validation-form" action="/usuario-web/index" novalidate="novalidate" method="post" role="form">

                <div class="controls">
                    <div class="col-md-4">
                        <label class="control-label text-info" for="name"><?php echo "Nome do usuário" ?></label>
                        <?php echo $this->formElement($form->get("ds_nome")) ?>
                        <?php echo $this->formElementErrors($form->get("ds_nome")) ?>
                    </div>
                </div>

                <div class="controls">
                    <div class="col-md-4">
                        <label class="control-label text-info" for="name"><?php echo "Login do usuário" ?></label>
                        <?php echo $this->formElement($form->get("ds_usuario")) ?>
                        <?php echo $this->formElementErrors($form->get("ds_usuario")) ?>
                    </div>
                </div>

                <div class="controls">
                    <div class="col-md-4">
                        <label class="control-label text-info" for="name"><?php echo utf8_encode("Email") ?></label>
                        <?php echo $this->formElement($form->get("ds_email")) ?>
                        <?php echo $this->formElementErrors($form->get("ds_email")) ?>
                    </div>
                </div>


                <div class="col-sm-12">
                    <hr>
                    <button type="submit" name="submit" id="btnSubmit" class="btn btn-primary btn" style="" value="">
                        <i class="fa fa-search"></i>
                        Pesquisar
                    </button>
                    <button type="button" name="buttonLimpar" class="btn btn-default btn" id="btnLimparFormulario" onclick="javascript:window.location.href='/usuario-web/index'" value="">
                        <i class="i i-back"></i>
                        Limpar
                    </button>
                </div>

            </form>
        </div>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="controls">
                    <div class="col-sm-12">
                        <button id="btnNovo" class="btn btn-success" style="float:right; margin-top:5px; margin-right:5px;">
                            <i class="i glyphicon-plus"></i>
                            Adicionar Usuário
                        </button>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                        <tr >
                            <!-- th nowrap>#</th -->
                            <th nowrap>Nome</th>
                            <th nowrap>Usuário</th>
                            <th nowrap>Email</th>
                            <th nowrap>Ativo</th>
                            <th nowrap>A&ccedil;&otilde;es</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (count($usuarios)) : ?>
                            <?php foreach ($usuarios as $dado): ?>
                                <tr>
                                    <td align="left"><?php echo utf8_encode($dado['DS_NOME']) ?></td>
                                    <td align="left"><?php echo utf8_encode($dado['DS_USUARIO']) ?></td>
                                    <td align="left"><?php echo utf8_encode($dado['DS_EMAIL']) ?></td>
                                    <td align="left"><?php echo ($dado['ST_ATIVO']== 'S' ? 'Sim' : 'Não') ?></td>
                                    <td  align="left">
                                        <?php if ($dado['ST_ATIVO']== 'S') : ?>
                                            <a href="/usuario-web/edicao?id=<?php echo $dado['CD_USUARIO_WEB'] ?>" title="Editar"><i class="fa fa-pencil"></i></a>
                                        | <a href="/usuario-web/inativar?id=<?php echo $dado['CD_USUARIO_WEB'] ?>"  title="Inativar"><i class="fa fa-trash-o"></i></a>
                                        <?php else: ?>
                                        <a href="/usuario-web/ativar?id=<?php echo $dado['CD_USUARIO_WEB'] ?>"  title="Ativar"><i class="fa fa-check"></i></a>
                                        <?php endif; ?>
                                    </td>
                                    </th>
                                </tr>

                            <?php endforeach; ?>
                        <?php endif; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th nowrap>Nome</th>
                            <th nowrap>Usuário</th>
                            <th nowrap>Email</th>
                            <th nowrap>Ativo</th>
                            <th nowrap>A&ccedil;&otilde;es</th>
                        </tr>
                        </tfoot>
                    </table>
                    <?php echo $this->paginationControl($usuarios, 'Sliding', 'partials/paginator/control.phtml') ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {

        $("#btnNovo").click(function() {
            window.location = "/usuario-web/cadastro";
        });
    });
</script>