<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">
				<h3 class="tit">Operadora de Cartão</h3>        
				<hr />   
				<form action="/tabela/cartao-cadastrar" method="post">
					<div class="col-xs-12 col-md-12">        
						<label>Descrição: </label>        
						<input class="form-control" type="text" name="DS_CARTAO" maxlength="50" required >
					</div>  						
					<div class="col-xs-3 col-md-3">        
						<label>Percentual Desconto: </label>        
						<input class="form-control" type="number" name="NR_PERCENTUAL_DESCONTO" maxlength="12"  >
					</div>  						
					<div class="col-xs-3 col-md-3">        
						<label>Dias para Reembolso: </label>        
						<input class="form-control" type="number" name="NR_DIAS_REEMBOLSO" maxlength="2" >
					</div>
					<div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/tabela/cartao"><button type="button" class="btn btn-default">
                                    <i class="i i-back"></i>
									Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>