<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de CFOP</h3>
                </div>
            </div>
        </div>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="controls">
                    <div class="col-sm-12">
                        <button id="btnNovo" class="btn btn-success" style="float:right; margin-top:5px; margin-right:5px;">
                            <i class="i glyphicon-plus"></i>
                             Adicionar CFOP
                        </button>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                            <tr >
                                <th nowrap>#</th>
                                <th nowrap>Descrição</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($cfop)) : ?>
                                <?php foreach ($cfop as $dado): ?>
                                    <tr>
                                        <td align="right"><?php echo $dado['CD_NATUREZA_OPERACAO']  ?></td>
                                        <td align="left"><?php echo utf8_encode($dado['DS_NATUREZA_OPERACAO']) ?></td>
                                        <td  align="center">
                                          <a href="/tabela/cfop-editar?id=<?php echo $dado['CD_NATUREZA_OPERACAO'] ?>" ><i class="fa fa-pencil"></i></a> <!--  |
                                            <a href="/cliente/remover?id=<?php echo $dado['CD_NATUREZA_OPERACAO'] ?>" ><i class="fa fa-trash-o"></i></a>-->
                                        </td>
                                        </th>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th nowrap>#</th>
                                <th nowrap>Descrição</th>
                                <th nowrap>A&ccedil;&otilde;es</th>
                            </tr>
                        </tfoot>
                    </table>
                    <?php// echo $this->paginationControl($formasPagamento, 'Sliding', 'partials/paginator/control.phtml') ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {

        $("#btnNovo").click(function() {
            window.location = "/tabela/cfop-cadastrar";
        });
    });
</script>
