<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">	
				<h3 class="tit">Editar Forma de Pagamento</h3>        
				<hr />   
				<form action="/tabela/forma-pagamento-editar" method="post">		
					<?php foreach($formaPagamento as $dado): ?>    
						<div class="col-xs-2 col-md-2">        
							<label>Cód: </label>    
							<input class="form-control" type="text" name="CD_TIPO_PAGAMENTO" maxlength="255" value="<?php echo $dado['CD_TIPO_PAGAMENTO'] ?>">    
						</div>	
						
						<div class="col-xs-10 col-md-10">        
							<label>Descrição: </label>        
							<input class="form-control" type="text" name="DS_TIPO_PAGAMENTO" maxlength="255" value="<?php echo utf8_encode($dado['DS_TIPO_PAGAMENTO']) ?>">    
						</div>
					<?php endforeach; ?>
					<div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/tabela/forma-pagamento"><button type="button" class="btn btn-default">
									Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>