<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">
				<h3 class="tit">Forma de Pagamento</h3>        
				<hr /> 
				<form action="/tabela/forma-pagamento-cadastrar" method="post">
					<div class="col-xs-10 col-md-10">        
						<label>Descrição: </label>        
						<input class="form-control" type="text" name="DS_TIPO_PAGAMENTO" maxlength="255" >
					</div>
					<div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/tabela/forma-pagamento"><button type="button" class="btn btn-default">
									<i class="i i-back"></i>
                                    Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>