USE [LOGIN]


CREATE TABLE [LOGIN].[dbo].TB_PERFIL_WEB(
	[CD_PERFIL_WEB] [int] NOT NULL,
	[DS_NOME] [varchar](55) NOT NULL,
	[ST_ATIVO] [char](1) NULL,
 CONSTRAINT [PK_TB_PERFIL_WEB] PRIMARY KEY (
	[CD_PERFIL_WEB] ASC
 )
);

ALTER TABLE [LOGIN].[dbo].TB_USUARIO_WEB
	ADD [CD_PERFIL_WEB] [int];

CREATE TABLE [LOGIN].[dbo].TB_PERFIL_WEB_MENUS(
	[CD_PERFIL_WEB] [int] NOT NULL,
	[CD_MENU] [int] NOT NULL
 CONSTRAINT [PK_TB_PERFIL_WEB_MENUS] PRIMARY KEY (
	[CD_PERFIL_WEB] ASC, [CD_MENU] ASC
 )
);

--Perfil Básico I
 UPDATE [LOGIN].[dbo].[TB_USUARIO_WEB]
  SET [CD_PERFIL_WEB] = 1
   WHERE [CD_USUARIO_WEB] = 6; -- bsbgestao

--Perfil Básico I
 UPDATE [LOGIN].[dbo].[TB_USUARIO_WEB]
  SET [CD_PERFIL_WEB] = 2
   WHERE [CD_PERFIL_WEB] is null;




