<section class="panel panel-default">
<div class="main">
<div class="row-fluid">
<div class="panel-body">
<div class="widget-header">
    <h3>Consulta de Atendimentos</h3>
</div>
<form class="form-horizontal"  id="validation-form" action="/mail/crm" novalidate="novalidate" method="post" role="form" enctype="multipart/form-data">
<fieldset>
    <legend>Cliente</legend>
    <div class="controls" >
        <div class="col-md-9">
            <label class="control-label text-info" for="name">Nome:</label><br>
            <input name="dsNome" id="dsNome" class="form-control" value="<?php echo $post['dsNome'] ?>" maxlength="255" />
        </div>
    </div>
    <div class="controls">
        <div class="col-md-3">
            <label class="control-label text-info" for="name">Sexo</label>
            <br><input type="radio" name="rdSexo" value="1" class="form-vertical" <?php
            if ($post['rdSexo'] == 1) {
                echo 'checked="checked"';
            }
            ?>>Feminino
            <br><input type="radio" name="rdSexo" value="2" class="form-vertical" <?php
            if ($post['rdSexo'] == 2) {
                echo 'checked="checked"';
            }
            ?>>Masculino
        </div>
    </div>
    <div class="col-sm-12">&nbsp;</div>
</fieldset>
<fieldset>
    <legend>Aniversariantes</legend>
    <div class="controls">
        <div class="col-md-1">
            <label class="control-label text-info" for="name">Dia</label>
            <input name="diaAniversario" id="diaAniversario" class="form-control" value="<?php echo $post['diaAniversario'] ?>" />
        </div>
    </div>
    <div class="controls">
        <div class="col-md-2">
            <label class="control-label text-info" for="name">Mês</label>
            <select name="mesAniversario" id="mesAniversario" class="form-control" value="" >
                <option value="">Selecione</option>
                <option value="1" <?php
                if ($post['mesAniversario'] == 1) {
                    echo 'selected="selected"';
                }
                ?>>Janeiro</option>
                <option value="2" <?php
                if ($post['mesAniversario'] == 2) {
                    echo 'selected="selected"';
                }
                ?>>Fevereiro</option>
                <option value="3" <?php
                if ($post['mesAniversario'] == 3) {
                    echo 'selected="selected"';
                }
                ?>>Março</option>
                <option value="4" <?php
                if ($post['mesAniversario'] == 4) {
                    echo 'selected="selected"';
                }
                ?>>Abril</option>
                <option value="5" <?php
                if ($post['mesAniversario'] == 5) {
                    echo 'selected="selected"';
                }
                ?>>Maio</option>
                <option value="6" <?php
                if ($post['mesAniversario'] == 6) {
                    echo 'selected="selected"';
                }
                ?>>Junho</option>
                <option value="7" <?php
                if ($post['mesAniversario'] == 7) {
                    echo 'selected="selected"';
                }
                ?>>Julho</option>
                <option value="8" <?php
                if ($post['mesAniversario'] == 8) {
                    echo 'selected="selected"';
                }
                ?>>Agosto</option>
                <option value="9" <?php
                if ($post['mesAniversario'] == 9) {
                    echo 'selected="selected"';
                }
                ?>>Setembro</option>
                <option value="10" <?php
                if ($post['mesAniversario'] == 10) {
                    echo 'selected="selected"';
                }
                ?>>Outubro</option>
                <option value="11" <?php
                if ($post['mesAniversario'] == 11) {
                    echo 'selected="selected"';
                }
                ?>>Novembro</option>
                <option value="12" <?php
                if ($post['mesAniversario'] == 12) {
                    echo 'selected="selected"';
                }
                ?>>Dezembro</option>
            </select>
        </div>
    </div>

    <div class="col-sm-12">&nbsp;</div>
</fieldset>
<fieldset>
    <legend>Atendimento/Ausência</legend>
    <div class="controls">
        <div class="col-md-4">
            <label class="control-label text-info" for="name">Tipo de Atendimento</label>
            <select name="tpAtendimento" id="tpAtendimento" class="form-control">
                <option value="">Selecione...</option>
                <option value="1" <?php
                if ($post['tpAtendimento'] == 1) {
                    echo 'selected="selected"';
                }
                ?>>Clientes Top 100</option>

                <option value="3" <?php
                if ($post['tpAtendimento'] == 3) {
                    echo 'selected="selected"';
                }
                ?>>Clientes Top 400</option>

                <option value="2" <?php
                if ($post['tpAtendimento'] == 2) {
                    echo 'selected="selected"';
                }
                ?>>Todos os Cliente Atendidos</option>

                <option value="4" <?php
                if ($post['tpAtendimento'] == 4) {
                    echo 'selected="selected"';
                }
                ?>>Clientes Ausentes</option>
            </select>
        </div>
    </div>
    <div class="controls">
        <div class="col-md-3" style="padding-right:0px;">
            <label class="control-label text-info" for="name">Período</label>
            <br><input type="radio" name="rdAusencia" value="0" class="rdAusencia form-vertical" <?php
            if ($post['rdAusencia'] == 0) {
                echo 'checked="checked"';
            }
            ?>>Intervalo
            <br><input type="radio" name="rdAusencia" value="1" class="rdAusencia form-vertical" <?php
            if ($post['rdAusencia'] == 1) {
                echo 'checked="checked"';
            }
            ?>>Dias
        </div>
    </div>
    <div class="controls" id="divAusencia1" style="display: none;">
        <div class="col-md-3">
            <label class="control-label text-info" for="name">Dias</label>
            <input name="dtAusencia" id="dtAusencia" class="form-control" value="<?php echo $post['dtAusencia'] ?>" maxlength="4" style="width: 50px;" />
        </div>
    </div>
    <div class="controls"  id="divAusencia2">
        <div class="col-md-2">
            <label class="control-label text-info" for="name">Período</label>
            <input id="dtAusenciaIni" name="dtAusenciaIni" class="dataP form-control" value="<?php echo $post['dtAusenciaIni'] ?>" maxlength="10" />
        </div>
        <div class="col-md-2">
            <label class="control-label text-info" for="name">&nbsp;</label>
            <input id="dtAusenciaFim" name="dtAusenciaFim" class="dataP form-control" value="<?php echo $post['dtAusenciaFim'] ?>" maxlength="10" />
        </div>
    </div>
    <div class="col-sm-12">&nbsp;</div>
</fieldset>
<fieldset>
    <legend>Ordenação</legend>
    <div class="controls">
        <div class="col-md-3">
            <?php //var_dump($post);exit; ?>
            <br><input type="radio" name="rdOrdenacao" value="0" class="form-vertical" <?php
            if ($post['rdOrdenacao'] == 0) {
                echo 'checked="checked"';
            }
            ?>> Data
            <input type="radio" name="rdOrdenacao" value="1" class="form-vertical" <?php
            if ($post['rdOrdenacao'] == 1) {
                echo 'checked="checked"';
            }
            ?>> Nome
        </div>
    </div>
    <div class="col-sm-12">&nbsp;</div>
</fieldset>
<div class="controls">
    <div class="col-sm-12">&nbsp;</div>
    <div class="btn-group btn-group col-sm-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default voltar">
                <i class="i i-back"></i>
                Limpar
            </button>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-primary pesquisar">
                <i class="i i-search"></i>
                Pesquisar
            </button>
        </div>
    </div>
    <br />
</div>
<div class="controls">
    <div class="col-md-12" style="height: 350px;overflow-y: scroll;">
        <label class="control-label text-info">Relação de Clientes</label>
        <table class="table table-striped">
            <thead>
            <tr>
                <th><input type="checkbox" class="selectAll" name="selectAll" id="selectAll" value="1"/></th>
                <th>Nome do Cliente</th>
                <th>Fone 1</th>
                <th>Fone 2</th>
                <th>Email</th>
                <th>Ultimo Atendimento</th>
                <th><?php echo $qtd ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            if ($arrMail) {
                foreach ($arrMail as $result) {
                    $ultimoAtendimento = NULL;
                    if ($result['dt_horario']) {
                        $ultimoAtendimento = date('d/m/Y', strtotime($result['dt_horario']));
                    }

                    if (isset($post['selectCliente']))
                        $ck = (in_array($result['CD_CLIENTE'], $post['selectCliente'])) ? 'checked="checked"' : '';

                    echo '<tr>
                                                <td><input type="checkbox" name="selectCliente[]" id="selectCliente" ' . $ck . ' value="' . $result['CD_CLIENTE'] . '"/></td>
                                                <td>' . utf8_encode($result['DS_NOME_RAZAO_SOCIAL']) . '</td>
                                                <td>' . $result['DS_FONE1'] . '</td>
                                                <td>' . $result['DS_FONE2'] . '</td>
                                                <td>' . $result['DS_EMAIL'] . '</td>
                                                <td>' . $ultimoAtendimento . '</td>
                                                <td>' . $result['QTD'] . '</td>
                                            </tr>';
                }
            }
            ?>
            </tbody>
        </table>

    </div>
</div>

<fieldset class="col-md-12">
    <legend>Email</legend>
    <div class="controls">

        <div class="controls">
            <div class="col-md-12">
                <label class="control-label text-info" for="name">Assunto</label>
                <input class="form-control" value="<?php echo $post['txtAssunto'] ?>" name="txtAssunto" id="txtAssunto" />
            </div>
        </div>

        <div class="controls">
            <div class="col-md-12">
                <label class="control-label text-info" for="name">Texto da Mensagem</label>
                <textarea class="form-control" name="txtMensagem" id="txtMensagem" cols="5"><?php echo $post['txtMensagem'] ?></textarea>
            </div>
        </div>

        <div class="controls">
            <div class="col-md-6">
                <label class="control-label text-info" for="name">Anexo</label>
                <input type="file" class="multi" id="anexo" name="anexo[]"/>
            </div>
        </div>
    </div>
</fieldset>
<div class="controls">
    <div class="col-md-12">&nbsp;</div>
    <div class="btn-group btn-group-justified col-md-12">

        <div class="btn-group">
            <button type="button" class="btn btn-default relatorio">
                <i class="i i-chart"></i>
                Imprimir Relatório
            </button>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-default planilha">
                <i class="i i-list"></i>
                Imprimir Planilha
            </button>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-default enviaremail">
                <i class="i i-mail"></i>
                Enviar Email
            </button>
        </div>

    </div>
    <br />
</div>
</form>
</div>
</div>
</div>
</section>

<!--<script type="text/javascript" src="/js/nicEdit/nicEdit-latest.js"></script> 
<script type="text/javascript">
//<![CDATA[
        bkLib.onDomLoaded(function() {
            new nicEditor().panelInstance('txtMensagem');
        });
  //]]>
  </script>-->

<script type="text/javascript">

tinymce.init({
        selector: "textarea",
        theme: "modern",
        width: 680,
        height: 300,
        language: "pt_BR",
        plugins: [
             "advlist autolink link image lists charmap print preview hr anchor pagebreak",
             "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
             "table contextmenu directionality emoticons paste textcolor "
       ],
        relative_urls: false,
        browser_spellcheck : true,
        filemanager_title:"Responsive Filemanager",
        external_filemanager_path:"/js/tinymce/ResponsiveFilemanager-master/filemanager/",
        external_plugins: { "filemanager" : "/js/tinymce/ResponsiveFilemanager-master/filemanager/plugin.min.js"},
        codemirror: {
        indentOnInit: true, // Whether or not to indent code on init. 
        path: 'CodeMirror'
      },
       image_advtab: true,
       toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
       toolbar2: "| responsivefilemanager | image | media | link unlink anchor | print preview code  | youtube | qrcode | flickr | picasa | colorpicker forecolor backcolor"
});


$('.dataP').datepicker(
    {
        format: 'dd/mm/yyyy',
        language: 'pt-BR',
        todayBtn: "linked"
    }
);
$('#anexo').MultiFile(
    {
        STRING: {
            remove: 'X',
            denied: 'Você não pode selecionar um arquivo $ext.\nTente novamente...',
            file: '$file',
            selected: 'Arquivo selecionado: $file',
            duplicate: 'O arquivo ja foi selecionado:\n$file'
        }
    }
);
$(document).ready(function() {
    $('.rdAusencia').click(function() {
        if (this.value == 1)
        {
            $('#divAusencia1').show();
            $('#divAusencia2').hide();
        }
        else
        {
            $('#divAusencia2').show();
            $('#divAusencia1').hide();
        }
    });
    validaSelecionado = function()
    {
        var p = false;
        $("input[name='selectCliente[]']").each(function() {
            if (this.checked)
            {
                p = true;
            }
        });
        return p;
    }

    <?php if ($post['rdAusencia'] == 0) { ?>
    $('#divAusencia2').show();
    $('#divAusencia1').hide();
    <?php } ?>

    $('.enviaremail').click(function() {
        if (validaSelecionado())
        {
            if ($('#txtAssunto').val() == '')
            {
                alert('Preencha o assunto da mensagem!');
                return false;
            }
            if ($('textarea #txtMensagem').val() == '')
            {
                alert('Preencha o texto da mensagem!');
                return false;
            }

            $('#validation-form').attr('action', '/mail/send-mail')
            $('#validation-form').submit();
            $('#validation-form').removeAttr('action');
        }
        else
        {
            alert('Selecione ao menos um cliente!');
        }
    });
    $('.pesquisar').click(function() {
        if($('#tpAtendimento').val() == '2'){
            if($('#dtAusenciaIni').val() == '' || $('#dtAusenciaFim').val() == ''){
                alert('Informe o Período!');
            }else{
                $('#validation-form').submit();
            }
        }else if($('#tpAtendimento').val() == '4'){
            if($('#dtAusenciaIni').val() == '' || $('#dtAusenciaFim').val() == ''){
                if($('#dtAusencia').val() == ''){
                    alert('Informe o período ou dias de ausência!');
                }else{
                    $('#validation-form').submit();
                }
            }else{
                $('#validation-form').submit();
            }
        }else if
        (
            $('#dsNome').val() != '' ||
            $('#tpAtendimento').val() != '' ||
            $('#dtAusencia').val() != '' ||
            $('#diaAniversario').val() != '' ||
            $('#mesAniversario').val() != '' ||
            $('#dtAusenciaIni').val() != '' ||
            $('#dtAusenciaFim').val() != ''
        ){
            $('#validation-form').submit();
        }else{
            alert('Informe ao menos um filtro!')
        }
    });
    $('.planilha').click(function() {
        if (validaSelecionado())
        {
            $('#validation-form').attr('action', '/mail/gerar-planilha');
            $('#validation-form').attr('target', '_blank');
            $('#validation-form').submit();
            $('#validation-form').removeAttr('action');
            $('#validation-form').removeAttr('target');
        }
        else
        {
            alert('Selecione ao menos um cliente!');
        }
    });
    $('.relatorio').click(function() {
        if (validaSelecionado())
        {
            $('#validation-form').attr('action', '/mail/relatorio');
            $('#validation-form').attr('target', '_blank');
            $('#validation-form').submit();
            $('#validation-form').removeAttr('action');
            $('#validation-form').removeAttr('target');
        }
        else
        {
            alert('Selecione ao menos um cliente!');
        }
    });
    $('.voltar').click(function() {
        $('#dsNome').val('');
        $('#tpAtendimento').val('');
        $('#dtAusencia').val('');
        $('#diaAniversario').val('');
        $('#mesAniversario').val('');
        $('#dtAusenciaIni').val('');
        $('#dtAusenciaFim').val('');
        document.getElementById('dsNome').disabled = false;
        document.getElementById('tpAtendimento').disabled = false;
        document.getElementById('dtAusencia').disabled = false;
        document.getElementById('diaAniversario').disabled = false;
        document.getElementById('mesAniversario').disabled = false;
        document.getElementById('dtAusenciaIni').disabled = false;
        document.getElementById('dtAusenciaFim').disabled = false;
    });
    $('#dsNome').change(function(){
        if($('#dsNome').val() == ''){
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('dtAusencia').disabled = false;
            document.getElementById('diaAniversario').disabled = false;
            document.getElementById('mesAniversario').disabled = false;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
        }else{
            document.getElementById('tpAtendimento').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = true;
            document.getElementById('dtAusenciaFim').disabled = true;
            $('#tpAtendimento').val('');
            $('#dtAusencia').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
            $('#dtAusenciaIni').val('');
            $('#dtAusenciaFim').val('');
        }
    });
    $('#tpAtendimento').change(function(){
        if($('#tpAtendimento').val() == ''){
            document.getElementById('dsNome').disabled = false;
            document.getElementById('dtAusencia').disabled = false;
            document.getElementById('diaAniversario').disabled = false;
            document.getElementById('mesAniversario').disabled = false;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
        }else{
            document.getElementById('dsNome').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
            $('#dsNome').val('');
            $('#dtAusencia').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
        }
        if($('#tpAtendimento').val() == '2'){
            document.getElementById('dsNome').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
            $('#dsNome').val('');
            $('#dtAusencia').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
        }
        if($('#tpAtendimento').val() == '4'){
            document.getElementById('dsNome').disabled = true;
            document.getElementById('dtAusencia').disabled = false;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
            $('#dsNome').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
        }
    });
    $('#dtAusencia').change(function(){
        if($('#dtAusencia').val() == ''){
            document.getElementById('dsNome').disabled = false;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('diaAniversario').disabled = false;
            document.getElementById('mesAniversario').disabled = false;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
        }else{
            document.getElementById('dsNome').disabled = true;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = true;
            document.getElementById('dtAusenciaFim').disabled = true;
            $('#dsNome').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
            $('#dtAusenciaIni').val('');
            $('#dtAusenciaFim').val('');
        }
    });
    $('#diaAniversario').change(function(){
        if($('#diaAniversario').val() == ''){
            document.getElementById('dsNome').disabled = false;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('dtAusencia').disabled = false;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
        }else{
            document.getElementById('dsNome').disabled = true;
            document.getElementById('tpAtendimento').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = true;
            document.getElementById('dtAusenciaFim').disabled = true;
            $('#dsNome').val('');
            $('#tpAtendimento').val('');
            $('#dtAusencia').val('');
            $('#dtAusenciaIni').val('');
            $('#dtAusenciaFim').val('');
        }
    });
    $('#mesAniversario').change(function(){
        if($('#mesAniversario').val() == ''){
            document.getElementById('dsNome').disabled = false;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('dtAusencia').disabled = false;
            document.getElementById('dtAusenciaIni').disabled = false;
            document.getElementById('dtAusenciaFim').disabled = false;
        }else{
            document.getElementById('dsNome').disabled = true;
            document.getElementById('tpAtendimento').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            document.getElementById('dtAusenciaIni').disabled = true;
            document.getElementById('dtAusenciaFim').disabled = true;
            $('#dsNome').val('');
            $('#tpAtendimento').val('');
            $('#dtAusencia').val('');
            $('#dtAusenciaIni').val('');
            $('#dtAusenciaFim').val('');
        }
    });
    $('#dtAusenciaIni').change(function(){
        if($('#dtAusenciaIni').val() == ''){
            document.getElementById('dsNome').disabled = false;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('diaAniversario').disabled = false;
            document.getElementById('mesAniversario').disabled = false;
            document.getElementById('dtAusencia').disabled = false;
        }else{
            document.getElementById('dsNome').disabled = true;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            $('#dsNome').val('');
            $('#dtAusencia').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
        }
    });
    $('#dtAusenciaFim').change(function(){
        if($('#dtAusenciaFim').val() == ''){
            document.getElementById('dsNome').disabled = false;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('diaAniversario').disabled = false;
            document.getElementById('mesAniversario').disabled = false;
            document.getElementById('dtAusencia').disabled = false;
        }else{
            document.getElementById('dsNome').disabled = true;
            document.getElementById('tpAtendimento').disabled = false;
            document.getElementById('diaAniversario').disabled = true;
            document.getElementById('mesAniversario').disabled = true;
            document.getElementById('dtAusencia').disabled = true;
            $('#dsNome').val('');
            $('#dtAusencia').val('');
            $('#diaAniversario').val('');
            $('#mesAniversario').val('');
        }
    });
});
</script>