<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">
				<h3 class="tit">Cadastrar perfil do sistema</h3>
				<hr />   
				<form action="/perfil-web/cadastro" method="post">
					<div class="col-xs-6 col-md-6">
						<label>Nome: </label>
						<input class="form-control" type="text" name="ds_nome" maxlength="50" placeholder="Nome do perfil" required>
					</div>

                    <div class="col-xs-12 col-md-12">
                        <br/>
                     <label>Funcionalidades do Perfil: </label>
					</div>
                    <div class="col-md-10">
                        <div class="col-xs-3 col-md-3">
                            <label>Painel Inicial</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="35" checked readonly/>&nbsp;Painel Inicial e ACL diversos
                            </label>
                            <hr/>
                        </div>

                        <div class="col-xs-3 col-md-3">
                            <label>Menu Controle de acesso </label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="2" />&nbsp;Menus do sistema
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="3" />&nbsp;Perfis do sistema
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="4" />&nbsp; Usuários Web
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Cadastros </label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="6" />&nbsp;Clientes
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="7" />&nbsp;Serviço/Mercadoria
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="8" />&nbsp;CFOP
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="9" />&nbsp;Cartões
                            </label>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="10" />&nbsp;Forma de Pagamento
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Agenda</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="11" />&nbsp;Agenda
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Pedido</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="12" />&nbsp;Pedido
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Caixa</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="13" />&nbsp;Caixa
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Contas à Pagar</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="19" />&nbsp;Contas à Pagar
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Contas à Receber</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="20" />&nbsp;Contas à Receber
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Nota Fiscal Eletrônica</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="15" />&nbsp;Emitir NF-e
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="16" />&nbsp;Listar NF-e
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="34" />&nbsp;Inutilizar NF-e
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="17" />&nbsp;Consulta(Receita)
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="18" />&nbsp;Configurar
                            </label>
                            <hr/>
                        </div>

                        <div class="col-xs-3 col-md-3">
                            <label>Menu Relatórios</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="22" />&nbsp;Atendimento - Produtos / Serviços Vendidos
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="23" />&nbsp;Notas
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="24" />&nbsp;Pedidos
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="25" />Agendamentos
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="26" />&nbsp;Caixa
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="27" />&nbsp;Resumo de Caixa
                            </label>

                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="28" />&nbsp;Invent&aacute;rio de Estoque
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="29" />&nbsp;Vendas Mensais Por Tipo de Pagamento
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="30" />&nbsp;Multi-Loja
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu CRM</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="32" />&nbsp;Análise
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="cd_menu[]" id="ckMenu" value="33" />&nbsp;E-mail
                            </label>
                            <hr/>
                        </div>

                        <div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/perfil-web/index"><button type="button" class="btn btn-default">
                                    <i class="i i-back"></i>
									Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
			