<section class="panel panel-default">
    <div class="main">
		<div class="row-fluid">
            <div class="panel-body">
				<h3 class="tit">Editar Perfil do sistema</h3>
				<hr />   
				<form action="/perfil/editar" method="post">
					<div class="col-xs-6 col-md-6">
						<label>Nome: </label>
						<input class="form-control" type="text" name="NM_PERFIL" maxlength="50" placeholder="Nome do perfil" required>
					</div>

                    <div class="col-xs-12 col-md-12">
                        <br/>
                     <label>Funcionalidades do Perfil: </label>
					</div>
                    <div class="col-md-10">
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Controle de acesso </label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Perfis do sistema
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoCheque" value="2" checked/>&nbsp; Usuários
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Cadastros </label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoCartao" value="5" checked/>&nbsp;Clientes
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoCartao" value="6" checked/>&nbsp;Serviço/Mercadoria
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoCheque" value="7" checked/>&nbsp;CFOP
                            </label>
                            <br>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="8" checked/>&nbsp;Cartões
                            </label>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="8" checked/>&nbsp;Forma de Pagamento
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Agenda</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Agenda
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Pedido</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Pedido
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Caixa</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Caixa
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Contas à Pagar</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Contas à Pagar
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Contas à Receber</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Contas à Receber
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu Nota Fiscal Eletrônica</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Emitir NF-e
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Listar NF-e
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Consulta(Receita)
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Configurar
                            </label>
                            <hr/>
                        </div>

                        <div class="col-xs-3 col-md-3">
                            <label>Menu Relatórios</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Atendimento - Produtos / Serviços Vendidos
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Notas
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Pedidos
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>Agendamentos
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Caixa
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Resumo de Caixa
                            </label>

                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Invent&aacute;rio de Estoque
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Vendas Mensais Por Tipo de Pagamento
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Multi-Loja
                            </label>
                            <hr/>
                        </div>
                        <div class="col-xs-3 col-md-3">
                            <label>Menu CRM</label>
                        </div>
                        <div class="col-md-3">
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;Análise
                            </label>
                            <br/>
                            <label>
                                <input type="checkbox" name="tipoPagamento" id="tipoPagamentoDinheiro" value="1" checked/>&nbsp;E-mail
                            </label>
                            <hr/>
                        </div>

                        <div class="controls">
						<div class="col-md-12">&nbsp;</div>
						<div class="btn-group btn-group-justified col-md-12">
							<div class="col-md-9">&nbsp;</div>
							<div class="col-md-3">
								<button type="submit" class="btn btn-primary">
									Salvar
								</button>
								<a href="/perfil/index"><button type="button" class="btn btn-default">
                                    <i class="i i-back"></i>
									Cancelar
								</button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
			