<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de Perfis do Sistema</h3>
                </div>
            </div>
        </div>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="controls">
                    <div class="col-sm-12">
                        <button id="btnNovo" class="btn btn-success" style="float:right; margin-top:5px; margin-right:5px;">
                            <i class="i glyphicon-plus"></i>
                            Adicionar Perfil
                        </button>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                        <tr >
                            <th nowrap>#</th>
                            <th nowrap>Nome do Perfil</th>
                            <th nowrap>Ativo</th>
                            <th nowrap>A&ccedil;&otilde;es</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (count($perfis)) : ?>
                            <?php foreach ($perfis as $dado): ?>
                                <tr>
                                    <td align="right"><?php echo utf8_encode($dado['CD_PERFIL_WEB'])  ?></td>
                                    <td align="left"><?php echo utf8_encode($dado['DS_NOME']) ?></td>
                                    <td align="left"><?php echo ($dado['ST_ATIVO']== 'S' ? 'Sim' : 'Não') ?></td>
                                    <td  align="left">
                                        <?php if ($dado['ST_ATIVO']== 'S') : ?>
                                            <a href="/perfil-web/edicao?id=<?php echo $dado['CD_PERFIL_WEB'] ?>" title="Editar"><i class="fa fa-pencil"></i></a>
                                        | <a href="/perfil-web/inativar?id=<?php echo $dado['CD_PERFIL_WEB'] ?>"  title="Inativar"><i class="fa fa-trash-o"></i></a>
                                        <?php else: ?>
                                        <a href="/perfil-web/ativar?id=<?php echo $dado['CD_PERFIL_WEB'] ?>"  title="Ativar"><i class="fa fa-check"></i></a>
                                        <?php endif; ?>
                                    </td>
                                    </th>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th nowrap>#</th>
                            <th nowrap>Nome do Perfil</th>
                            <th nowrap>Ativo</th>
                            <th nowrap>A&ccedil;&otilde;es</th
                        </tr>
                        </tfoot>
                    </table>
                    <?php echo $this->paginationControl($perfis, 'Sliding', 'partials/paginator/control-no-form.phtml') ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {

        $("#btnNovo").click(function() {
            window.location = "/perfil-web/cadastro";
        });
    });
</script>