<?php if (count($messages)) : ?>
    <?php
    foreach ($messages as $value):
        $key = key($value);
        $message = current($value);
        ?>
        <div class="alert alert-<?php echo $key ?>">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<section class="panel panel-default">
    <div class="main">
        <div class="row-fluid">
            <div class="panel-body">
                <div class="widget-header">
                    <h3>Listagem de Perfis do Sistema</h3>
                </div>
            </div>
        </div>
        <div class="row-fluid" id="result">
            <div class="widget stacked" >
                <div class="controls">
                    <div class="col-sm-12">
                        <button id="btnNovo" class="btn btn-success" style="float:right; margin-top:5px; margin-right:5px;">
                            <i class="i glyphicon-plus"></i>
                            Adicionar Perfil
                        </button>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped m-b-none" data-ride="datatables">
                        <thead>
                        <tr >
                            <!-- th nowrap>#</th -->
                            <th nowrap>Nome do Perfil</th>
                            <th nowrap>Status</th>
                            <th nowrap>A&ccedil;&otilde;es</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php //if (count($cartoes)) : ?>
                            <?php //foreach ($cartoes as $dado): ?>
                                <tr>
                                    <!-- td align="right"><?php //echo $cliente->CD_CLIENTE  ?></td -->
                                    <td align="left">Nome do perfil 1<?php //echo utf8_encode($dado['NM_PERFIL']) ?></td>
                                    <td align="left">Ativo <?php //echo utf8_encode($dado['ST_PERFIL']) ?></td>
                                    <td  align="left">
                                        <a href="/perfil/editar?id=<?php //echo $dado['CD_PERFIL'] ?>" title="Editar"><i class="fa fa-pencil"></i></a>
                                        <a href="/perfil/index"  title="Remover/Inativar"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                    </th>
                                </tr>
                                <tr>
                                    <!-- td align="right"><?php //echo $cliente->CD_CLIENTE  ?></td -->
                                    <td align="left">Nome do perfil 2<?php //echo utf8_encode($dado['NM_PERFIL']) ?></td>
                                    <td align="left">Inativo <?php //echo utf8_encode($dado['ST_PERFIL']) ?></td>
                                    <td  align="left">
                                        &nbsp;
                                    </td>
                                    </th>
                                </tr>
                            <?php //endforeach; ?>
                        <?php //endif; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <!-- th nowrap>#</th -->
                            <th nowrap>Nome do Perfil</th>
                            <th nowrap>Status</th>
                            <th nowrap>A&ccedil;&otilde;es</th
                        </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {

        $("#btnNovo").click(function() {
            window.location = "/perfil/cadastrar";
        });
    });
</script>